unit CM.Lang.Table;

{ GERADO por tools\i18n\generate-lang-table.ps1 a partir de tools\i18n\translations.tsv - nao editar.
  Cada linha: portugues (a chave), ingles, frances, alemao. }

interface

const
  LangRows: array[0..624] of array[0..3] of string = (
  ('Projeto', 'Project', 'Projet', 'Projekt'),
  ('Mapa', 'Map', 'Carte', 'Karte'),
  ('Checklist', 'Checklist', 'Checklist', 'Checkliste'),
  ('Painel', 'Dashboard', 'Synthèse', 'Dashboard'),
  ('Alternar entre tema claro e escuro', 'Switch between light and dark theme', 'Basculer entre le thème clair et sombre', 'Zwischen hellem und dunklem Design wechseln'),
  ('Configure o projeto, analise o código-fonte e exporte as páginas HTML.', 'Set up the project, analyze the source code and export the HTML pages.', 'Configurez le projet, analysez le code source et exportez les pages HTML.', 'Richten Sie das Projekt ein, analysieren Sie den Quellcode und exportieren Sie die HTML-Seiten.'),
  ('Mapa de código', 'Code map', 'Carte du code', 'Codekarte'),
  ('Checklist de código', 'Code checklist', 'Checklist du code', 'Code-Checkliste'),
  ('%s  ·  %d ficheiros  ·  %d métodos', '%s  ·  %d files  ·  %d methods', '%s  ·  %d fichiers  ·  %d méthodes', '%s  ·  %d Dateien  ·  %d Methoden'),
  ('  ·  ainda sem análise (separador Projeto)', '  ·  not analyzed yet (Project tab)', '  ·  pas encore analysé (onglet Projet)', '  ·  noch nicht analysiert (Reiter Projekt)'),
  ('PROJETO FINALIZADO', 'PROJECT FINALIZED', 'PROJET FINALISÉ', 'PROJEKT ABGESCHLOSSEN'),
  ('Idioma', 'Language', 'Langue', 'Sprache'),
  ('Mudar o idioma da aplicação', 'Change the application language', 'Changer la langue de l''application', 'Sprache der Anwendung ändern'),
  ('Idioma: %s', 'Language: %s', 'Langue : %s', 'Sprache: %s'),
  ('As definições estavam danificadas: foram recuperadas da cópia de segurança.', 'The settings were damaged: they were restored from the backup copy.', 'Les paramètres étaient endommagés : ils ont été restaurés à partir de la copie de sauvegarde.', 'Die Einstellungen waren beschädigt: Sie wurden aus der Sicherungskopie wiederhergestellt.'),
  (' A recomeçar.', ' Starting over.', ' Redémarrage à zéro.', ' Es wird neu begonnen.'),
  ('O progresso estava danificado: foi recuperado da cópia de segurança.', 'The progress data was damaged: it was restored from the backup copy.', 'La progression était endommagée : elle a été restaurée à partir de la copie de sauvegarde.', 'Der Fortschritt war beschädigt: Er wurde aus der Sicherungskopie wiederhergestellt.'),
  ('O histórico estava danificado: foi recuperado da cópia de segurança.', 'The history was damaged: it was restored from the backup copy.', 'L''historique était endommagé : il a été restauré à partir de la copie de sauvegarde.', 'Der Verlauf war beschädigt: Er wurde aus der Sicherungskopie wiederhergestellt.'),
  ('as definições', 'the settings', 'les paramètres', 'die Einstellungen'),
  ('o progresso guardado', 'the saved progress', 'la progression enregistrée', 'den gespeicherten Fortschritt'),
  ('o histórico guardado', 'the saved history', 'l''historique enregistré', 'den gespeicherten Verlauf'),
  ('Não foi possível ler %s: o ficheiro está danificado e não há cópia de segurança.', 'Could not read %s: the file is damaged and there is no backup copy.', 'Impossible de lire %s : le fichier est endommagé et il n''y a pas de copie de sauvegarde.', '%s konnte nicht gelesen werden: Die Datei ist beschädigt und es gibt keine Sicherungskopie.'),
  ('Não foi possível ler %s (%s).', 'Could not read %s (%s).', 'Impossible de lire %s (%s).', '%s konnte nicht gelesen werden (%s).'),
  ('Não foi possível guardar: ', 'Could not save: ', 'Impossible d''enregistrer : ', 'Speichern nicht möglich: '),
  ('A consultar o SonarQube…', 'Querying SonarQube…', 'Consultation de SonarQube…', 'SonarQube wird abgefragt…'),
  ('Cada projeto guarda o seu progresso.', 'Each project keeps its own progress.', 'Chaque projet garde sa propre progression.', 'Jedes Projekt speichert seinen eigenen Fortschritt.'),
  ('Primeiros passos', 'Getting started', 'Premiers pas', 'Erste Schritte'),
  ('1. Escolha a pasta do projeto e/ou o plano (.md)', '1. Choose the project folder and/or the plan (.md)', '1. Choisissez le dossier du projet et/ou le plan (.md)', '1. Projektordner und/oder Plan (.md) auswählen'),
  ('2. Clique em «Analisar projeto»', '2. Click “Analyze project”', '2. Cliquez sur « Analyser le projet »', '2. Auf „Projekt analysieren“ klicken'),
  ('3. Reveja no Mapa, na Checklist e no Painel', '3. Review it in the Map, the Checklist and the Dashboard', '3. Passez en revue dans la Carte, la Checklist et la Synthèse', '3. In Karte, Checkliste und Dashboard prüfen'),
  ('Novo projeto', 'New project', 'Nouveau projet', 'Neues Projekt'),
  ('Configuração', 'Settings', 'Configuration', 'Konfiguration'),
  ('Nome do projeto', 'Project name', 'Nom du projet', 'Projektname'),
  ('ex.: AssisTEC', 'e.g. AssisTEC', 'p. ex. AssisTEC', 'z. B. AssisTEC'),
  ('Localização do projeto (pasta raiz a analisar)', 'Project location (root folder to analyze)', 'Emplacement du projet (dossier racine à analyser)', 'Projektort (zu analysierender Stammordner)'),
  ('Pasta onde guardar as páginas HTML', 'Folder where the HTML pages are saved', 'Dossier où enregistrer les pages HTML', 'Ordner zum Speichern der HTML-Seiten'),
  ('Documento do plano (.md) — opcional: estrutura e código previstos', 'Plan document (.md) — optional: planned structure and code', 'Document du plan (.md) — facultatif : structure et code prévus', 'Plandokument (.md) – optional: geplante Struktur und geplanter Code'),
  ('Pastas a ignorar (separadas por vírgulas)', 'Folders to ignore (comma-separated)', 'Dossiers à ignorer (séparés par des virgules)', 'Zu ignorierende Ordner (durch Kommas getrennt)'),
  ('Abrir a página no navegador depois de exportar', 'Open the page in the browser after exporting', 'Ouvrir la page dans le navigateur après l''exportation', 'Seite nach dem Export im Browser öffnen'),
  ('Acompanhar alterações na pasta do projeto', 'Watch for changes in the project folder', 'Suivre les modifications dans le dossier du projet', 'Änderungen im Projektordner verfolgen'),
  ('https://github.com/utilizador/repositorio', 'https://github.com/user/repository', 'https://github.com/utilisateur/depot', 'https://github.com/benutzer/repository'),
  ('Em branco = predefinidas. Analisa .pas, .dpr e .dpk. Com pasta e plano, o Mapa mostra o que falta e o que sobra.', 'Blank = defaults. Analyzes .pas, .dpr and .dpk. With a folder and a plan, the Map shows what is missing and what is extra.', 'Vide = valeurs par défaut. Analyse .pas, .dpr et .dpk. Avec un dossier et un plan, la Carte montre ce qui manque et ce qui est en trop.', 'Leer = Standardwerte. Analysiert .pas, .dpr und .dpk. Mit Ordner und Plan zeigt die Karte, was fehlt und was überzählig ist.'),
  ('SonarQube (opcional)', 'SonarQube (optional)', 'SonarQube (facultatif)', 'SonarQube (optional)'),
  ('Cada utilizador decide se o usa. O endereço e o token ficam nos teus dados;', 'Each user decides whether to use it. The address and token stay in your data;', 'Chaque utilisateur décide de l''utiliser ou non. L''adresse et le jeton restent dans vos données ;', 'Jeder Benutzer entscheidet selbst, ob er es nutzt. Adresse und Token bleiben in Ihren Daten;'),
  ('o token é cifrado e só funciona neste computador e nesta conta do Windows.', 'the token is encrypted and only works on this computer and this Windows account.', 'le jeton est chiffré et ne fonctionne que sur cet ordinateur et ce compte Windows.', 'der Token ist verschlüsselt und funktioniert nur auf diesem Computer und mit diesem Windows-Konto.'),
  ('Usar o SonarQube neste computador', 'Use SonarQube on this computer', 'Utiliser SonarQube sur cet ordinateur', 'SonarQube auf diesem Computer verwenden'),
  ('Endereço do servidor', 'Server address', 'Adresse du serveur', 'Serveradresse'),
  ('Token de utilizador', 'User token', 'Jeton utilisateur', 'Benutzer-Token'),
  ('cola aqui o token (My Account › Security)', 'paste the token here (My Account › Security)', 'collez ici le jeton (My Account › Security)', 'Token hier einfügen (My Account › Security)'),
  ('Chave deste projeto no SonarQube', 'This project''s key in SonarQube', 'Clé de ce projet dans SonarQube', 'Schlüssel dieses Projekts in SonarQube'),
  ('ex.: CodeManager', 'e.g. CodeManager', 'p. ex. CodeManager', 'z. B. CodeManager'),
  ('Testar ligação', 'Test connection', 'Tester la connexion', 'Verbindung testen'),
  ('A testar…', 'Testing…', 'Test en cours…', 'Wird getestet…'),
  ('Ações', 'Actions', 'Actions', 'Aktionen'),
  ('Analisar projeto', 'Analyze project', 'Analyser le projet', 'Projekt analysieren'),
  ('Exportar mapa (HTML)', 'Export map (HTML)', 'Exporter la carte (HTML)', 'Karte exportieren (HTML)'),
  ('Exportar checklist (HTML)', 'Export checklist (HTML)', 'Exporter la checklist (HTML)', 'Checkliste exportieren (HTML)'),
  ('Fechar projeto como finalizado', 'Close project as finalized', 'Clôturer le projet comme finalisé', 'Projekt als abgeschlossen markieren'),
  ('Reabrir projeto', 'Reopen project', 'Rouvrir le projet', 'Projekt wieder öffnen'),
  ('Remover projeto', 'Remove project', 'Supprimer le projet', 'Projekt entfernen'),
  ('Escolha a pasta do projeto e clique em «Analisar projeto».', 'Choose the project folder and click “Analyze project”.', 'Choisissez le dossier du projet et cliquez sur « Analyser le projet ».', 'Wählen Sie den Projektordner und klicken Sie auf „Projekt analysieren“.'),
  ('Resumo da análise', 'Analysis summary', 'Résumé de l''analyse', 'Analyseübersicht'),
  ('(sem nome)', '(unnamed)', '(sans nom)', '(ohne Namen)'),
  ('(sem pasta)', '(no folder)', '(sans dossier)', '(ohne Ordner)'),
  ('FINALIZADO', 'FINALIZED', 'FINALISÉ', 'ABGESCHLOSSEN'),
  ('Escolha a pasta raiz do projeto a analisar', 'Choose the root folder of the project to analyze', 'Choisissez le dossier racine du projet à analyser', 'Wählen Sie den Stammordner des zu analysierenden Projekts'),
  ('Escolha a pasta onde guardar as páginas HTML', 'Choose the folder where the HTML pages are saved', 'Choisissez le dossier où enregistrer les pages HTML', 'Wählen Sie den Ordner zum Speichern der HTML-Seiten'),
  ('Escolha o documento do plano (Markdown)', 'Choose the plan document (Markdown)', 'Choisissez le document du plan (Markdown)', 'Wählen Sie das Plandokument (Markdown)'),
  ('Markdown (*.md;*.markdown)|*.md;*.markdown|Todos os ficheiros (*.*)|*.*', 'Markdown (*.md;*.markdown)|*.md;*.markdown|All files (*.*)|*.*', 'Markdown (*.md;*.markdown)|*.md;*.markdown|Tous les fichiers (*.*)|*.*', 'Markdown (*.md;*.markdown)|*.md;*.markdown|Alle Dateien (*.*)|*.*'),
  ('Remover o projeto "%s" da lista? O progresso guardado será apagado (os ficheiros do projeto não são tocados).', 'Remove the project "%s" from the list? The saved progress will be deleted (the project files are not touched).', 'Supprimer le projet « %s » de la liste ? La progression enregistrée sera effacée (les fichiers du projet ne sont pas touchés).', 'Projekt „%s“ aus der Liste entfernen? Der gespeicherte Fortschritt wird gelöscht (die Projektdateien bleiben unberührt).'),
  ('Fechar o projeto como finalizado? O mapa exportado passa a ter o selo "PROJETO FINALIZADO".', 'Close the project as finalized? The exported map will carry the "PROJECT FINALIZED" seal.', 'Clôturer le projet comme finalisé ? La carte exportée portera le sceau « PROJET FINALISÉ ».', 'Projekt als abgeschlossen markieren? Die exportierte Karte erhält den Stempel „PROJEKT ABGESCHLOSSEN“.'),
  ('Projeto finalizado', 'Project finalized', 'Projet finalisé', 'Projekt abgeschlossen'),
  ('Projeto reaberto', 'Project reopened', 'Projet rouvert', 'Projekt wieder geöffnet'),
  ('  ·  a acompanhar alterações', '  ·  watching for changes', '  ·  suivi des modifications actif', '  ·  Änderungen werden verfolgt'),
  ('novo: %s (%d métodos)', 'new: %s (%d methods)', 'nouveau : %s (%d méthodes)', 'neu: %s (%d Methoden)'),
  ('removido: ', 'removed: ', 'supprimé : ', 'entfernt: '),
  ('%s (%d métodos novos ou alterados)', '%s (%d new or changed methods)', '%s (%d méthodes nouvelles ou modifiées)', '%s (%d neue oder geänderte Methoden)'),
  (' atualizado', ' updated', ' mis à jour', ' aktualisiert'),
  ('%d ficheiros (%d novos, %d alterados, %d removidos)', '%d files (%d new, %d changed, %d removed)', '%d fichiers (%d nouveaux, %d modifiés, %d supprimés)', '%d Dateien (%d neu, %d geändert, %d entfernt)'),
  ('Acompanhar · %s · %s', 'Watching · %s · %s', 'Suivi · %s · %s', 'Verfolgen · %s · %s'),
  ('Atualizado: ', 'Updated: ', 'Mis à jour : ', 'Aktualisiert: '),
  ('A analisar…', 'Analyzing…', 'Analyse en cours…', 'Wird analysiert…'),
  ('Indique o nome do projeto.', 'Enter the project name.', 'Indiquez le nom du projet.', 'Geben Sie den Projektnamen ein.'),
  ('Indique uma pasta de projeto válida.', 'Enter a valid project folder.', 'Indiquez un dossier de projet valide.', 'Geben Sie einen gültigen Projektordner an.'),
  ('Indique uma pasta de projeto ou um documento de plano válido.', 'Enter a valid project folder or plan document.', 'Indiquez un dossier de projet ou un document de plan valide.', 'Geben Sie einen gültigen Projektordner oder ein gültiges Plandokument an.'),
  ('A procurar unidades .pas/.dpr/.dpk…', 'Looking for .pas/.dpr/.dpk units…', 'Recherche des unités .pas/.dpr/.dpk…', 'Suche nach .pas/.dpr/.dpk-Units…'),
  ('Documento do plano não encontrado: ', 'Plan document not found: ', 'Document du plan introuvable : ', 'Plandokument nicht gefunden: '),
  ('Falhou a leitura do plano: ', 'Could not read the plan: ', 'Échec de la lecture du plan : ', 'Der Plan konnte nicht gelesen werden: '),
  ('ERRO: ', 'ERROR: ', 'ERREUR : ', 'FEHLER: '),
  ('Falhou a análise do projeto.', 'The project analysis failed.', 'L''analyse du projet a échoué.', 'Die Projektanalyse ist fehlgeschlagen.'),
  ('Análise concluída: %d ficheiros · %d métodos em %d units.', 'Analysis complete: %d files · %d methods in %d units.', 'Analyse terminée : %d fichiers · %d méthodes dans %d unités.', 'Analyse abgeschlossen: %d Dateien · %d Methoden in %d Units.'),
  (' Plano: %.0f%% dos ficheiros e %.0f%% dos métodos já existem.', ' Plan: %.0f%% of the files and %.0f%% of the methods already exist.', ' Plan : %.0f%% des fichiers et %.0f%% des méthodes existent déjà.', ' Plan: %.0f%% der Dateien und %.0f%% der Methoden sind bereits vorhanden.'),
  ('Plano analisado: %d ficheiros · %d métodos em %d units (sem pasta de código).', 'Plan analyzed: %d files · %d methods in %d units (no code folder).', 'Plan analysé : %d fichiers · %d méthodes dans %d unités (sans dossier de code).', 'Plan analysiert: %d Dateien · %d Methoden in %d Units (ohne Code-Ordner).'),
  ('Nada para analisar.', 'Nothing to analyze.', 'Rien à analyser.', 'Nichts zu analysieren.'),
  (' %d aviso(s) do plano.', ' %d plan warning(s).', ' %d avertissement(s) du plan.', ' %d Warnung(en) zum Plan.'),
  ('Pastas', 'Folders', 'Dossiers', 'Ordner'),
  ('Ficheiros', 'Files', 'Fichiers', 'Dateien'),
  ('Métodos', 'Methods', 'Méthodes', 'Methoden'),
  ('Units com métodos', 'Units with methods', 'Unités avec méthodes', 'Units mit Methoden'),
  ('Ficheiros concluídos', 'Files done', 'Fichiers terminés', 'Erledigte Dateien'),
  ('Métodos revistos', 'Methods reviewed', 'Méthodes revues', 'Geprüfte Methoden'),
  ('Analise o projeto primeiro.', 'Analyze the project first.', 'Analysez d''abord le projet.', 'Analysieren Sie zuerst das Projekt.'),
  ('Indique a pasta onde guardar as páginas HTML.', 'Enter the folder where the HTML pages are saved.', 'Indiquez le dossier où enregistrer les pages HTML.', 'Geben Sie den Ordner zum Speichern der HTML-Seiten an.'),
  ('Mapa exportado: ', 'Map exported: ', 'Carte exportée : ', 'Karte exportiert: '),
  ('Checklist exportada: ', 'Checklist exported: ', 'Checklist exportée : ', 'Checkliste exportiert: '),
  ('Falhou a exportação: ', 'Export failed: ', 'Échec de l''exportation : ', 'Export fehlgeschlagen: '),
  ('Progresso', 'Progress', 'Progression', 'Fortschritt'),
  ('Estado da revisão', 'Review status', 'État de la revue', 'Prüfstatus'),
  ('Atualizar', 'Refresh', 'Actualiser', 'Aktualisieren'),
  ('Sincronizar S', 'Sync S', 'Synchroniser S', 'S synchronisieren'),
  ('Só alterados', 'Changed only', 'Modifiés seulement', 'Nur geänderte'),
  ('Voltar a «por rever»', 'Back to “to review”', 'Remettre « à revoir »', 'Zurück auf „zu prüfen“'),
  ('Plano', 'Plan', 'Plan', 'Plan'),
  ('Filtrar por camada', 'Filter by layer', 'Filtrer par couche', 'Nach Schicht filtern'),
  ('Expandir tudo', 'Expand all', 'Tout développer', 'Alle öffnen'),
  ('Colapsar tudo', 'Collapse all', 'Tout réduire', 'Alle schließen'),
  ('Abrir métodos', 'Open methods', 'Ouvrir les méthodes', 'Methoden auf'),
  ('Fechar métodos', 'Close methods', 'Fermer les méthodes', 'Methoden zu'),
  ('Markdown', 'Markdown', 'Markdown', 'Markdown'),
  ('Exportar HTML', 'Export HTML', 'Exporter en HTML', 'HTML exportieren'),
  ('Exportar', 'Export', 'Exporter', 'Exportieren'),
  ('Importar', 'Import', 'Importer', 'Importieren'),
  ('Reiniciar progresso', 'Reset progress', 'Réinitialiser la progression', 'Fortschritt zurücksetzen'),
  ('Fechar nota', 'Close note', 'Fermer la note', 'Notiz schließen'),
  ('Nota sobre este ficheiro…', 'Note about this file…', 'Note sur ce fichier…', 'Notiz zu dieser Datei…'),
  ('Analise um projeto para ver a checklist.', 'Analyze a project to see the checklist.', 'Analysez un projet pour voir la checklist.', 'Analysieren Sie ein Projekt, um die Checkliste zu sehen.'),
  ('Filtrar por nome ou pasta…   ( / )', 'Filter by name or folder…   ( / )', 'Filtrer par nom ou dossier…   ( / )', 'Nach Name oder Ordner filtern…   ( / )'),
  ('Só prioritários', 'Priority only', 'Prioritaires seulement', 'Nur priorisierte'),
  ('0 / 0 ficheiros', '0 / 0 files', '0 / 0 fichiers', '0 / 0 Dateien'),
  ('%d / %d ficheiros', '%d / %d files', '%d / %d fichiers', '%d / %d Dateien'),
  ('Por implementar', 'To implement', 'À implémenter', 'Noch umzusetzen'),
  ('Extra no código', 'Extra in the code', 'En plus dans le code', 'Zusätzlich im Code'),
  ('%d fich. · %d mét.', '%d files · %d meth.', '%d fich. · %d mét.', '%d Dat. · %d Meth.'),
  ('Servidor', 'Server', 'Serveur', 'Server'),
  ('a consultar…', 'querying…', 'consultation…', 'Abfrage läuft…'),
  ('sem dados', 'no data', 'aucune donnée', 'keine Daten'),
  ('aprovada', 'passed', 'réussie', 'bestanden'),
  ('reprovada', 'failed', 'échouée', 'nicht bestanden'),
  ('com avisos', 'with warnings', 'avec avertissements', 'mit Warnungen'),
  ('sem gate', 'no gate', 'sans gate', 'kein Gate'),
  ('desconhecida', 'unknown', 'inconnue', 'unbekannt'),
  ('Quality gate', 'Quality gate', 'Quality gate', 'Quality Gate'),
  ('Problemas abertos', 'Open issues', 'Problèmes ouverts', 'Offene Probleme'),
  ('Ficheiros com problemas', 'Files with issues', 'Fichiers avec problèmes', 'Dateien mit Problemen'),
  ('Atualizado', 'Updated', 'Mis à jour', 'Aktualisiert'),
  ('O servidor ainda não tem ficheiros analisados para este projeto (sem análises, ', 'The server has no analyzed files for this project yet (no analyses, ', 'Le serveur n''a pas encore de fichiers analysés pour ce projet (aucune analyse, ', 'Der Server hat für dieses Projekt noch keine analysierten Dateien (keine Analysen, '),
  ('ou o SonarQube não analisa Delphi sem um plugin).', 'or SonarQube does not analyze Delphi without a plugin).', 'ou SonarQube n''analyse pas Delphi sans plugin).', 'oder SonarQube analysiert Delphi nicht ohne Plugin).'),
  ('Ainda não há dados do SonarQube. Usa «Atualizar».', 'There is no SonarQube data yet. Use “Refresh”.', 'Il n''y a pas encore de données SonarQube. Utilisez « Actualiser ».', 'Es liegen noch keine SonarQube-Daten vor. Verwenden Sie „Aktualisieren“.'),
  ('Marcar «S» nos ficheiros que o SonarQube analisou sem problemas abertos e tirá-lo aos que têm problemas? ', 'Mark “S” on the files SonarQube analyzed with no open issues and remove it from those with issues? ', 'Cocher « S » pour les fichiers analysés par SonarQube sans problème ouvert et le retirer à ceux qui en ont ? ', '„S“ bei den Dateien setzen, die SonarQube ohne offene Probleme analysiert hat, und bei Dateien mit Problemen entfernen? '),
  ('Os ficheiros que o SonarQube não conhece ficam como estão.', 'Files unknown to SonarQube stay as they are.', 'Les fichiers inconnus de SonarQube restent inchangés.', 'Dateien, die SonarQube nicht kennt, bleiben unverändert.'),
  ('Sonar: %d ficheiros marcados, %d desmarcados', 'Sonar: %d files marked, %d unmarked', 'Sonar : %d fichiers cochés, %d décochés', 'Sonar: %d Dateien markiert, %d Markierungen entfernt'),
  ('Commit atual', 'Current commit', 'Commit actuel', 'Aktueller Commit'),
  ('Mudaram desde a revisão', 'Changed since review', 'Modifiés depuis la revue', 'Seit der Prüfung geändert'),
  ('%s: %d ficheiros revistos mudaram desde a revisão', '%s: %d reviewed files changed since review', '%s : %d fichiers revus ont changé depuis la revue', '%s: %d geprüfte Dateien seit der Prüfung geändert'),
  ('Nenhum ficheiro revisto mudou desde a revisão', 'No reviewed file has changed since review', 'Aucun fichier revu n''a changé depuis la revue', 'Keine geprüfte Datei wurde seit der Prüfung geändert'),
  ('Voltar a «por rever» os %d ficheiros que mudaram desde a revisão? ', 'Set the %d files that changed since review back to “to review”? ', 'Remettre « à revoir » les %d fichiers modifiés depuis la revue ? ', 'Die %d seit der Prüfung geänderten Dateien wieder auf „zu prüfen“ setzen? '),
  ('Ficam sem estado de revisão; Compila, Sonar, prioridade e notas mantêm-se.', 'They lose their review status; Builds, Sonar, priority and notes are kept.', 'Ils perdent leur état de revue ; Compile, Sonar, priorité et notes sont conservés.', 'Sie verlieren ihren Prüfstatus; Kompiliert, Sonar, Priorität und Notizen bleiben erhalten.'),
  ('Ficheiros repostos como por rever', 'Files set back to to-review', 'Fichiers remis à revoir', 'Dateien wieder auf „zu prüfen“ gesetzt'),
  ('Nota · ', 'Note · ', 'Note · ', 'Notiz · '),
  ('Analise um projeto primeiro.', 'Analyze a project first.', 'Analysez d''abord un projet.', 'Analysieren Sie zuerst ein Projekt.'),
  ('Markdown copiado', 'Markdown copied', 'Markdown copié', 'Markdown kopiert'),
  ('Progresso (*.json)|*.json', 'Progress (*.json)|*.json', 'Progression (*.json)|*.json', 'Fortschritt (*.json)|*.json'),
  ('-checklist-progresso-', '-checklist-progress-', '-checklist-progression-', '-checkliste-fortschritt-'),
  ('Progresso exportado', 'Progress exported', 'Progression exportée', 'Fortschritt exportiert'),
  ('Ficheiro inválido: ', 'Invalid file: ', 'Fichier non valide : ', 'Ungültige Datei: '),
  ('Progresso importado', 'Progress imported', 'Progression importée', 'Fortschritt importiert'),
  ('Reiniciar o progresso, notas e prioridades de todos os ficheiros deste projeto?', 'Reset the progress, notes and priorities of all files in this project?', 'Réinitialiser la progression, les notes et les priorités de tous les fichiers de ce projet ?', 'Fortschritt, Notizen und Prioritäten aller Dateien dieses Projekts zurücksetzen?'),
  ('Progresso reiniciado', 'Progress reset', 'Progression réinitialisée', 'Fortschritt zurückgesetzt'),
  ('Estatísticas', 'Statistics', 'Statistiques', 'Statistik'),
  ('Vista', 'View', 'Vue', 'Ansicht'),
  ('Exportar e imprimir estrutura', 'Export and print structure', 'Exporter et imprimer la structure', 'Struktur exportieren und drucken'),
  ('Incluir métodos', 'Include methods', 'Inclure les méthodes', 'Methoden einbeziehen'),
  ('Incluir estado e notas', 'Include status and notes', 'Inclure l''état et les notes', 'Status und Notizen einbeziehen'),
  ('TXT', 'TXT', 'TXT', 'TXT'),
  ('CSV (Excel)', 'CSV (Excel)', 'CSV (Excel)', 'CSV (Excel)'),
  ('JSON', 'JSON', 'JSON', 'JSON'),
  ('Imprimir…', 'Print…', 'Imprimer…', 'Drucken…'),
  ('As checkboxes C (Compila) e S (Sonar) ficam guardadas com o progresso do projeto.', 'The C (Builds) and S (Sonar) checkboxes are saved with the project''s progress.', 'Les cases C (Compile) et S (Sonar) sont enregistrées avec la progression du projet.', 'Die Kontrollkästchen C (Kompiliert) und S (Sonar) werden mit dem Projektfortschritt gespeichert.'),
  ('Analise um projeto para ver o mapa de código.', 'Analyze a project to see the code map.', 'Analysez un projet pour voir la carte du code.', 'Analysieren Sie ein Projekt, um die Codekarte zu sehen.'),
  ('Filtrar por pasta, ficheiro ou método…   ( / )', 'Filter by folder, file or method…   ( / )', 'Filtrer par dossier, fichier ou méthode…   ( / )', 'Nach Ordner, Datei oder Methode filtern…   ( / )'),
  ('Ficheiros · Compila', 'Files · Builds', 'Fichiers · Compile', 'Dateien · Kompiliert'),
  ('Ficheiros · Sonar', 'Files · Sonar', 'Fichiers · Sonar', 'Dateien · Sonar'),
  ('Métodos · Compila', 'Methods · Builds', 'Méthodes · Compile', 'Methoden · Kompiliert'),
  ('Métodos · Sonar', 'Methods · Sonar', 'Méthodes · Sonar', 'Methoden · Sonar'),
  ('Plano · ficheiros', 'Plan · files', 'Plan · fichiers', 'Plan · Dateien'),
  ('Plano · métodos', 'Plan · methods', 'Plan · méthodes', 'Plan · Methoden'),
  ('Exportado: ', 'Exported: ', 'Exporté : ', 'Exportiert: '),
  ('Enviada para a impressora: 1 página', 'Sent to the printer: 1 page', 'Envoyé à l''imprimante : 1 page', 'An den Drucker gesendet: 1 Seite'),
  ('Enviada para a impressora: %d páginas', 'Sent to the printer: %d pages', 'Envoyé à l''imprimante : %d pages', 'An den Drucker gesendet: %d Seiten'),
  ('Falhou a impressão: ', 'Printing failed: ', 'Échec de l''impression : ', 'Drucken fehlgeschlagen: '),
  ('Não há impressoras instaladas.', 'There are no printers installed.', 'Aucune imprimante n''est installée.', 'Es sind keine Drucker installiert.'),
  ('Impressora indisponível: ', 'Printer unavailable: ', 'Imprimante indisponible : ', 'Drucker nicht verfügbar: '),
  ('Analise um projeto para ver o painel.', 'Analyze a project to see the dashboard.', 'Analysez un projet pour voir la synthèse.', 'Analysieren Sie ein Projekt, um das Dashboard zu sehen.'),
  ('Ainda só há um registo: a curva aparece a partir do segundo dia', 'There is only one record so far: the curve appears from the second day', 'Il n''y a encore qu''un enregistrement : la courbe apparaît à partir du deuxième jour', 'Bisher gibt es nur einen Eintrag: Die Kurve erscheint ab dem zweiten Tag'),
  ('%s a %s · %d registos', '%s to %s · %d records', '%s au %s · %d enregistrements', '%s bis %s · %d Einträge'),
  ('Evolução do progresso', 'Progress over time', 'Évolution de la progression', 'Fortschrittsverlauf'),
  ('Progresso por camada', 'Progress by layer', 'Progression par couche', 'Fortschritt nach Schicht'),
  ('Ficheiros concluídos e por concluir', 'Files done and still to do', 'Fichiers terminés et restants', 'Erledigte und offene Dateien'),
  ('Concluídos', 'Done', 'Terminés', 'Erledigt'),
  ('Por concluir', 'To do', 'Restants', 'Offen'),
  ('%d%% do projeto', '%d%% of the project', '%d%% du projet', '%d%% des Projekts'),
  ('%d%% dos métodos', '%d%% of the methods', '%d%% des méthodes', '%d%% der Methoden'),
  ('%d%% dos ficheiros', '%d%% of the files', '%d%% des fichiers', '%d%% der Dateien'),
  ('Compila', 'Builds', 'Compile', 'Kompiliert'),
  ('Sonar', 'Sonar', 'Sonar', 'Sonar'),
  ('Compila e Sonar por camada', 'Builds and Sonar by layer', 'Compile et Sonar par couche', 'Kompiliert und Sonar nach Schicht'),
  ('Ficheiros com cada marca', 'Files with each mark', 'Fichiers avec chaque marque', 'Dateien mit jeder Markierung'),
  ('Métodos mais complexos', 'Most complex methods', 'Méthodes les plus complexes', 'Komplexeste Methoden'),
  ('Os %d com maior complexidade ciclomática', 'The %d with the highest cyclomatic complexity', 'Les %d de plus forte complexité cyclomatique', 'Die %d mit der höchsten zyklomatischen Komplexität'),
  ('Métodos com mais parâmetros', 'Methods with the most parameters', 'Méthodes avec le plus de paramètres', 'Methoden mit den meisten Parametern'),
  ('Os %d com mais parâmetros', 'The %d with the most parameters', 'Les %d avec le plus de paramètres', 'Die %d mit den meisten Parametern'),
  ('Métodos mais aninhados', 'Most deeply nested methods', 'Méthodes les plus imbriquées', 'Am tiefsten verschachtelte Methoden'),
  ('Os %d com maior aninhamento de blocos', 'The %d with the deepest block nesting', 'Les %d à l''imbrication de blocs la plus profonde', 'Die %d mit der tiefsten Blockverschachtelung'),
  ('complexidade cognitiva %d', 'cognitive complexity %d', 'complexité cognitive %d', 'kognitive Komplexität %d'),
  ('Complexidade cognitiva', 'Cognitive complexity', 'Complexité cognitive', 'Kognitive Komplexität'),
  ('Cognitiva', 'Cognitive', 'Cognitive', 'Kognitiv'),
  ('Métodos de maior complexidade cognitiva', 'Methods with the highest cognitive complexity', 'Méthodes à la plus forte complexité cognitive', 'Methoden mit der höchsten kognitiven Komplexität'),
  ('Os %d com maior complexidade cognitiva', 'The %d with the highest cognitive complexity', 'Les %d de plus forte complexité cognitive', 'Die %d mit der höchsten kognitiven Komplexität'),
  ('Complexidade cognitiva dos métodos', 'Cognitive complexity of methods', 'Complexité cognitive des méthodes', 'Kognitive Komplexität der Methoden'),
  ('Quantos métodos em cada nível (simples até 15, moderada até 25)', 'How many methods at each level (simple up to 15, moderate up to 25)', 'Combien de méthodes par niveau (simple jusqu''à 15, modérée jusqu''à 25)', 'Wie viele Methoden pro Stufe (einfach bis 15, mäßig bis 25)'),
  ('Complexidade', 'Complexity', 'Complexité', 'Komplexität'),
  ('Complexidade dos métodos', 'Method complexity', 'Complexité des méthodes', 'Methodenkomplexität'),
  ('Quantos métodos em cada nível (simples até 10, moderada até 20)', 'How many methods at each level (simple up to 10, moderate up to 20)', 'Combien de méthodes par niveau (simple jusqu''à 10, modérée jusqu''à 20)', 'Wie viele Methoden pro Stufe (einfach bis 10, mittel bis 20)'),
  ('Simples', 'Simple', 'Simple', 'Einfach'),
  ('Moderada', 'Moderate', 'Modérée', 'Mittel'),
  ('Alta', 'High', 'Élevée', 'Hoch'),
  ('Cobertura do plano por camada', 'Plan coverage by layer', 'Couverture du plan par couche', 'Plan-Abdeckung nach Schicht'),
  ('Ficheiros · %.0f%% do planeado já existe', 'Files · %.0f%% of what was planned already exists', 'Fichiers · %.0f%% du prévu existe déjà', 'Dateien · %.0f%% des Geplanten ist bereits vorhanden'),
  ('Implementados', 'Implemented', 'Implémentés', 'Umgesetzt'),
  ('Extra', 'Extra', 'En plus', 'Zusätzlich'),
  ('Plano e código', 'Plan and code', 'Plan et code', 'Plan und Code'),
  ('Cobertura: %.0f%% dos ficheiros · %.0f%% dos métodos', 'Coverage: %.0f%% of files · %.0f%% of methods', 'Couverture : %.0f%% des fichiers · %.0f%% des méthodes', 'Abdeckung: %.0f%% der Dateien · %.0f%% der Methoden'),
  ('Estado dos ficheiros', 'File status', 'État des fichiers', 'Dateistatus'),
  ('Em %d ficheiros', 'Across %d files', 'Sur %d fichiers', 'Über %d Dateien'),
  ('Em revisão', 'In review', 'En cours de revue', 'In Prüfung'),
  ('A alterar', 'To change', 'À modifier', 'Zu ändern'),
  ('Maiores units', 'Largest units', 'Plus grandes unités', 'Größte Units'),
  ('As %d com mais métodos', 'The %d with the most methods', 'Les %d avec le plus de méthodes', 'Die %d mit den meisten Methoden'),
  ('Métodos por ficheiro', 'Methods per file', 'Méthodes par fichier', 'Methoden pro Datei'),
  ('Quantos ficheiros têm cada número de métodos', 'How many files have each number of methods', 'Combien de fichiers ont chaque nombre de méthodes', 'Wie viele Dateien jeweils so viele Methoden haben'),
  ('Métodos por camada', 'Methods by layer', 'Méthodes par couche', 'Methoden nach Schicht'),
  ('Total: %d métodos', 'Total: %d methods', 'Total : %d méthodes', 'Gesamt: %d Methoden'),
  ('concluído', 'done', 'terminé', 'erledigt'),
  ('Sem dados para mostrar.', 'No data to show.', 'Aucune donnée à afficher.', 'Keine Daten anzuzeigen.'),
  ('(raiz)', '(root)', '(racine)', '(Stamm)'),
  ('1 método', '1 method', '1 méthode', '1 Methode'),
  ('Concluída automaticamente quando todos os métodos estiverem marcados', 'Completed automatically when all methods are checked', 'Terminé automatiquement lorsque toutes les méthodes sont cochées', 'Wird automatisch erledigt, sobald alle Methoden abgehakt sind'),
  ('Método revisto', 'Method reviewed', 'Méthode revue', 'Methode geprüft'),
  ('Marcar como concluída', 'Mark as done', 'Marquer comme terminé', 'Als erledigt markieren'),
  ('Estado: ', 'Status: ', 'État : ', 'Status: '),
  (' (vem dos métodos)', ' (derived from the methods)', ' (déduit des méthodes)', ' (aus den Methoden abgeleitet)'),
  (' — clica para mudar', ' — click to change', ' — cliquez pour changer', ' – zum Ändern klicken'),
  ('Marcar prioridade', 'Mark as priority', 'Marquer comme prioritaire', 'Als Priorität markieren'),
  ('Método compila sem erros', 'Method builds without errors', 'La méthode compile sans erreur', 'Methode kompiliert fehlerfrei'),
  ('Compila sem erros', 'Builds without errors', 'Compile sans erreur', 'Kompiliert fehlerfrei'),
  ('Método aprovado no SonarQube', 'Method approved in SonarQube', 'Méthode approuvée dans SonarQube', 'Methode in SonarQube freigegeben'),
  ('SonarQube aprovado', 'Approved in SonarQube', 'Approuvé dans SonarQube', 'In SonarQube freigegeben'),
  ('Mostrar/ocultar os métodos desta unit', 'Show/hide the methods of this unit', 'Afficher/masquer les méthodes de cette unité', 'Methoden dieser Unit ein-/ausblenden'),
  ('Nota', 'Note', 'Note', 'Notiz'),
  ('PLANEADO', 'PLANNED', 'PRÉVU', 'GEPLANT'),
  ('EXTRA', 'EXTRA', 'EN PLUS', 'EXTRA'),
  ('MOVIDO', 'MOVED', 'DÉPLACÉ', 'VERSCHOBEN'),
  ('Planeado: ainda não está implementado', 'Planned: not implemented yet', 'Prévu : pas encore implémenté', 'Geplant: noch nicht umgesetzt'),
  ('Planeado: ainda não existe no código', 'Planned: does not exist in the code yet', 'Prévu : n''existe pas encore dans le code', 'Geplant: im Code noch nicht vorhanden'),
  ('Extra: existe no código mas não está no plano', 'Extra: exists in the code but is not in the plan', 'En plus : existe dans le code mais pas dans le plan', 'Extra: im Code vorhanden, aber nicht im Plan'),
  ('Planeado em ', 'Planned in ', 'Prévu dans ', 'Geplant in '),
  ('SonarQube: %d problemas abertos (a pior: %s)', 'SonarQube: %d open issues (worst: %s)', 'SonarQube : %d problèmes ouverts (le pire : %s)', 'SonarQube: %d offene Probleme (schwerstes: %s)'),
  ('ficheiro', 'file', 'fichier', 'Datei'),
  ('ficheiros', 'files', 'fichiers', 'Dateien'),
  ('método', 'method', 'méthode', 'Methode'),
  ('métodos', 'methods', 'méthodes', 'Methoden'),
  ('pasta', 'folder', 'dossier', 'Ordner'),
  ('pastas', 'folders', 'dossiers', 'Ordner'),
  ('ALTERADO', 'CHANGED', 'MODIFIÉ', 'GEÄNDERT'),
  ('Por rever', 'To review', 'À revoir', 'Zu prüfen'),
  ('Precisa de alteração', 'Needs changes', 'À modifier', 'Änderung nötig'),
  ('Concluído', 'Done', 'Terminé', 'Erledigt'),
  ('bloqueante', 'blocker', 'bloquante', 'blockierend'),
  ('crítica', 'critical', 'critique', 'kritisch'),
  ('maior', 'major', 'majeure', 'schwerwiegend'),
  ('menor', 'minor', 'mineure', 'geringfügig'),
  ('informativa', 'info', 'informative', 'informativ'),
  ('1 linha · complexidade %d', '1 line · complexity %d', '1 ligne · complexité %d', '1 Zeile · Komplexität %d'),
  ('%d linhas · complexidade %d', '%d lines · complexity %d', '%d lignes · complexité %d', '%d Zeilen · Komplexität %d'),
  ('Mudou desde a revisão (alterações ainda por gravar no %s)', 'Changed since review (changes not yet committed to %s)', 'Modifié depuis la revue (modifications pas encore enregistrées dans %s)', 'Seit der Prüfung geändert (noch nicht in %s gespeicherte Änderungen)'),
  ('Mudou desde a revisão:', 'Changed since review:', 'Modifié depuis la revue :', 'Seit der Prüfung geändert:'),
  ('Texto (árvore)', 'Text (tree)', 'Texte (arborescence)', 'Text (Baum)'),
  ('-estrutura', '-structure', '-structure', '-struktur'),
  ('Sim', 'Yes', 'Oui', 'Ja'),
  ('Não', 'No', 'Non', 'Nein'),
  ('Pasta raiz: ', 'Root folder: ', 'Dossier racine : ', 'Stammordner: '),
  ('Gerado em: ', 'Generated on: ', 'Généré le : ', 'Erstellt am: '),
  ('Progresso: %d/%d ficheiros concluídos, %d/%d métodos revistos', 'Progress: %d/%d files done, %d/%d methods reviewed', 'Progression : %d/%d fichiers terminés, %d/%d méthodes revues', 'Fortschritt: %d/%d Dateien erledigt, %d/%d Methoden geprüft'),
  (' — nota: ', ' — note: ', ' — note : ', ' – Notiz: '),
  (' (prioritário)', ' (priority)', ' (prioritaire)', ' (priorisiert)'),
  ('  -- nota: ', '  -- note: ', '  -- note : ', '  -- Notiz: '),
  ('Estrutura do código — ', 'Code structure — ', 'Structure du code — ', 'Codestruktur — '),
  ('Estrutura do código', 'Code structure', 'Structure du code', 'Codestruktur'),
  ('Nível', 'Level', 'Niveau', 'Ebene'),
  ('Pasta', 'Folder', 'Dossier', 'Ordner'),
  ('Ficheiro', 'File', 'Fichier', 'Datei'),
  ('Camada', 'Layer', 'Couche', 'Schicht'),
  ('Classe', 'Class', 'Classe', 'Klasse'),
  ('Método', 'Method', 'Méthode', 'Methode'),
  ('Tipo', 'Type', 'Type', 'Typ'),
  ('Assinatura', 'Signature', 'Signature', 'Signatur'),
  ('Linhas', 'Lines', 'Lignes', 'Zeilen'),
  ('Prioritário', 'Priority', 'Prioritaire', 'Priorität'),
  ('Revisão', 'Review', 'Revue', 'Prüfung'),
  ('Página %d de %d', 'Page %d of %d', 'Page %d sur %d', 'Seite %d von %d'),
  ('Checklist de Código-Fonte — ', 'Source Code Checklist — ', 'Checklist du code source — ', 'Quellcode-Checkliste — '),
  (' [Compila]', ' [Builds]', ' [Compile]', ' [Kompiliert]'),
  (' [Sonar]', ' [Sonar]', ' [Sonar]', ' [Sonar]'),
  ('Raiz', 'Root', 'Racine', 'Stamm'),
  ('A analisar metodos... ', 'Analyzing methods... ', 'Analyse des méthodes... ', 'Methoden werden analysiert... '),
  ('A pasta do projecto nao existe: %s', 'The project folder does not exist: %s', 'Le dossier du projet n''existe pas : %s', 'Der Projektordner existiert nicht: %s'),
  ('Nao foi encontrada nenhuma unidade .pas/.dpr/.dpk em "%s" (fora das pastas ignoradas).', 'No .pas/.dpr/.dpk unit was found in "%s" (outside the ignored folders).', 'Aucune unité .pas/.dpr/.dpk n''a été trouvée dans « %s » (hors des dossiers ignorés).', 'In „%s“ wurde keine .pas/.dpr/.dpk-Unit gefunden (außerhalb der ignorierten Ordner).'),
  ('assinatura de método sem ficheiro associado — ignorada: ', 'method signature without an associated file — ignored: ', 'signature de méthode sans fichier associé — ignorée : ', 'Methodensignatur ohne zugehörige Datei – ignoriert: '),
  ('bloco de código sem caminho de ficheiro — ignorado', 'code block without a file path — ignored', 'bloc de code sans chemin de fichier — ignoré', 'Codeblock ohne Dateipfad – ignoriert'),
  ('%s: não foi possível ler o código (%s)', '%s: could not read the code (%s)', '%s : impossible de lire le code (%s)', '%s: Der Code konnte nicht gelesen werden (%s)'),
  ('O documento não contém nenhum ficheiro (.pas, .dpr ou .dpk).', 'The document does not contain any file (.pas, .dpr or .dpk).', 'Le document ne contient aucun fichier (.pas, .dpr ou .dpk).', 'Das Dokument enthält keine Datei (.pas, .dpr oder .dpk).'),
  ('O documento do plano não existe: %s', 'The plan document does not exist: %s', 'Le document du plan n''existe pas : %s', 'Das Plandokument existiert nicht: %s'),
  ('O ficheiro "%s" esta danificado e nao ha uma copia de seguranca valida.', 'The file "%s" is damaged and there is no valid backup copy.', 'Le fichier « %s » est endommagé et il n''y a pas de copie de sauvegarde valide.', 'Die Datei „%s“ ist beschädigt und es gibt keine gültige Sicherungskopie.'),
  ('O ficheiro "%s" nao existe.', 'The file "%s" does not exist.', 'Le fichier « %s » n''existe pas.', 'Die Datei „%s“ existiert nicht.'),
  ('Não foi possível ligar a ', 'Could not connect to ', 'Impossible de se connecter à ', 'Verbindung nicht möglich zu '),
  ('O servidor recusou o token (ou exige um token). Confirma-o nas definições.', 'The server rejected the token (or requires one). Check it in the settings.', 'Le serveur a refusé le jeton (ou en exige un). Vérifiez-le dans les paramètres.', 'Der Server hat den Token abgelehnt (oder verlangt einen). Prüfen Sie ihn in den Einstellungen.'),
  ('O token não tem permissão para ler este projeto. Usa um token de utilizador (My Account › Security › ', 'The token has no permission to read this project. Use a user token (My Account › Security › ', 'Le jeton n''a pas la permission de lire ce projet. Utilisez un jeton utilisateur (My Account › Security › ', 'Der Token hat keine Berechtigung, dieses Projekt zu lesen. Verwenden Sie einen Benutzer-Token (My Account › Security › '),
  ('User Token), não o de análise do sonar-scanner, de uma conta com a permissão «Browse» no projeto.', 'User Token), not the sonar-scanner analysis one, from an account with the “Browse” permission on the project.', 'User Token), pas celui d''analyse du sonar-scanner, d''un compte ayant la permission « Browse » sur le projet.', 'User Token), nicht den Analyse-Token des sonar-scanner, von einem Konto mit der Berechtigung „Browse“ für das Projekt.'),
  ('Não encontrei o projeto «', 'I could not find the project “', 'Projet introuvable : «', 'Das Projekt „'),
  ('» neste servidor.', '” on this server.', '» sur ce serveur.', '“ wurde auf diesem Server nicht gefunden.'),
  ('O servidor respondeu com o erro %d.', 'The server responded with error %d.', 'Le serveur a répondu avec l''erreur %d.', 'Der Server hat mit Fehler %d geantwortet.'),
  ('O servidor ainda não tem projetos analisados: corre primeiro o sonar-scanner (ci.bat sonar).', 'The server has no analyzed projects yet: run the sonar-scanner first (ci.bat sonar).', 'Le serveur n''a pas encore de projets analysés : exécutez d''abord le sonar-scanner (ci.bat sonar).', 'Der Server hat noch keine analysierten Projekte: Führen Sie zuerst den sonar-scanner aus (ci.bat sonar).'),
  ('Chaves que existem: ', 'Existing keys: ', 'Clés existantes : ', 'Vorhandene Schlüssel: '),
  ('Indica o endereço do servidor.', 'Enter the server address.', 'Indiquez l''adresse du serveur.', 'Geben Sie die Serveradresse ein.'),
  ('Ligado ao SonarQube ', 'Connected to SonarQube ', 'Connecté à SonarQube ', 'Verbunden mit SonarQube '),
  ('. Falta indicar a chave do projeto.', '. The project key is still missing.', '. Il manque la clé du projet.', '. Der Projektschlüssel fehlt noch.'),
  (': projeto «', ': project “', ': projet «', ': Projekt „'),
  ('» encontrado.', '” found.', '» trouvé.', '“ gefunden.'),
  ('Indica a chave do projeto no SonarQube.', 'Enter the project key in SonarQube.', 'Indiquez la clé du projet dans SonarQube.', 'Geben Sie den Projektschlüssel in SonarQube ein.'),
  ('As pastas <code>', 'The folders <code>', 'Les dossiers <code>', 'Die Ordner <code>'),
  ('</code> foram ignoradas nesta análise ', '</code> were ignored in this analysis ', '</code> ont été ignorés dans cette analyse ', '</code> wurden bei dieser Analyse ignoriert '),
  ('(dependências de terceiros, artefactos de build ou cópias de segurança do IDE) — ', '(third-party dependencies, build artifacts or IDE backup copies) — ', '(dépendances tierces, artefacts de build ou copies de sauvegarde de l''IDE) — ', '(Abhängigkeiten von Drittanbietern, Build-Artefakte oder IDE-Sicherungskopien) – '),
  ('não são código próprio.', 'they are not your own code.', 'ils ne font pas partie de votre propre code.', 'sie sind nicht der eigene Code.'),
  ('Projetos', 'Projects', 'Projets', 'Projekte'),
  ('Estrutura', 'Structure', 'Structure', 'Struktur'),
  ('A procurar unidades .pas/.dpr/.dpk...', 'Looking for .pas/.dpr/.dpk units...', 'Recherche des unités .pas/.dpr/.dpk...', 'Suche nach .pas/.dpr/.dpk-Units...'),
  ('Linha %d: %s', 'Line %d: %s', 'Ligne %d : %s', 'Zeile %d: %s'),
  ('<div class="finalized-banner">&#10003; PROJECTO FINALIZADO em ', '<div class="finalized-banner">&#10003; PROJECT FINALIZED on ', '<div class="finalized-banner">&#10003; PROJET FINALISÉ le ', '<div class="finalized-banner">&#10003; PROJEKT ABGESCHLOSSEN am '),
  ('Ou um repositório do GitHub (opcional, só leitura)', 'Or a GitHub repository (optional, read-only)', 'Ou un dépôt GitHub (facultatif, en lecture seule)', 'Oder ein GitHub-Repository (optional, schreibgeschützt)'),
  ('Atualizar do GitHub', 'Update from GitHub', 'Mettre à jour depuis GitHub', 'Von GitHub aktualisieren'),
  ('A obter %s do GitHub…', 'Fetching %s from GitHub…', 'Récupération de %s depuis GitHub…', '%s wird von GitHub geholt…'),
  ('A pasta indicada no endereço não existe no repositório.', 'The folder given in the address does not exist in the repository.', 'Le dossier indiqué dans l''adresse n''existe pas dans le dépôt.', 'Der in der Adresse angegebene Ordner existiert im Repository nicht.'),
  ('Indique o endereço do repositório no GitHub.', 'Enter the GitHub repository address.', 'Indiquez l''adresse du dépôt GitHub.', 'Geben Sie die Adresse des GitHub-Repositorys ein.'),
  ('Só são aceites repositórios do GitHub (github.com).', 'Only GitHub repositories (github.com) are accepted.', 'Seuls les dépôts GitHub (github.com) sont acceptés.', 'Es werden nur GitHub-Repositorys (github.com) akzeptiert.'),
  ('O endereço deve ser da forma https://github.com/dono/repositorio.', 'The address must look like https://github.com/owner/repository.', 'L''adresse doit être de la forme https://github.com/proprietaire/depot.', 'Die Adresse muss die Form https://github.com/besitzer/repository haben.'),
  ('O nome do dono ou do repositório tem caracteres inválidos.', 'The owner or repository name has invalid characters.', 'Le nom du propriétaire ou du dépôt contient des caractères non valides.', 'Der Name des Besitzers oder des Repositorys enthält ungültige Zeichen.'),
  ('O nome do ramo tem caracteres inválidos.', 'The branch name has invalid characters.', 'Le nom de la branche contient des caractères non valides.', 'Der Branch-Name enthält ungültige Zeichen.'),
  ('Repositório não encontrado, ou é privado e o Git não tem credenciais para o ler.', 'Repository not found, or it is private and Git has no credentials to read it.', 'Dépôt introuvable, ou il est privé et Git n''a pas les identifiants pour le lire.', 'Repository nicht gefunden, oder es ist privat und Git hat keine Zugangsdaten, um es zu lesen.'),
  ('Não foi possível ligar ao GitHub. Verifique a ligação à Internet.', 'Could not connect to GitHub. Check your Internet connection.', 'Impossible de se connecter à GitHub. Vérifiez votre connexion Internet.', 'Verbindung zu GitHub nicht möglich. Prüfen Sie Ihre Internetverbindung.'),
  ('O ramo indicado não existe neste repositório.', 'The given branch does not exist in this repository.', 'La branche indiquée n''existe pas dans ce dépôt.', 'Der angegebene Branch existiert in diesem Repository nicht.'),
  ('Projeto sem identificador válido.', 'Project without a valid identifier.', 'Projet sans identifiant valide.', 'Projekt ohne gültige Kennung.'),
  ('O Git não está instalado (ou não está no PATH): é preciso para ler um repositório.', 'Git is not installed (or not on the PATH): it is needed to read a repository.', 'Git n''est pas installé (ou n''est pas dans le PATH) : il est nécessaire pour lire un dépôt.', 'Git ist nicht installiert (oder nicht im PATH): Es wird zum Lesen eines Repositorys benötigt.'),
  ('Grafo', 'Graph', 'Graphe', 'Graph'),
  ('Grafo de dependências', 'Dependency graph', 'Graphe de dépendances', 'Abhängigkeitsgraph'),
  ('Dependências entre units', 'Dependencies between units', 'Dépendances entre unités', 'Abhängigkeiten zwischen Units'),
  ('Mapa de dependências', 'Dependency map', 'Carte des dépendances', 'Abhängigkeitskarte'),
  ('Units', 'Units', 'Unités', 'Units'),
  ('Unit', 'Unit', 'Unité', 'Unit'),
  ('Ligações', 'Links', 'Liens', 'Verknüpfungen'),
  ('Units externas', 'External units', 'Unités externes', 'Externe Units'),
  ('Ciclos', 'Cycles', 'Cycles', 'Zyklen'),
  ('Colunas do mapa', 'Map columns', 'Colonnes de la carte', 'Spalten der Karte'),
  ('Ligações por unit', 'Links per unit', 'Liens par unité', 'Verknüpfungen pro Unit'),
  ('Nenhum ciclo: as units não se usam em círculo.', 'No cycles: no units use each other in a circle.', 'Aucun cycle : aucune unité ne s''utilise en cercle.', 'Keine Zyklen: Keine Units verwenden sich gegenseitig im Kreis.'),
  ('Units que se usam umas às outras', 'Units that use each other', 'Unités qui s''utilisent mutuellement', 'Units, die sich gegenseitig verwenden'),
  ('Mais usadas', 'Most used', 'Les plus utilisées', 'Am häufigsten verwendet'),
  ('Mais dependentes', 'Most dependent', 'Les plus dépendantes', 'Am abhängigsten'),
  ('Usa', 'Uses', 'Utilise', 'Verwendet'),
  ('Usada por', 'Used by', 'Utilisée par', 'Verwendet von'),
  ('Ligações entre camadas', 'Links between layers', 'Liens entre couches', 'Verknüpfungen zwischen Schichten'),
  ('Não há ligações entre camadas diferentes.', 'There are no links between different layers.', 'Il n''y a pas de liens entre des couches différentes.', 'Es gibt keine Verknüpfungen zwischen verschiedenen Schichten.'),
  ('De', 'From', 'De', 'Von'),
  ('Para', 'To', 'Vers', 'Nach'),
  ('Units sem uso', 'Unused units', 'Unités inutilisées', 'Ungenutzte Units'),
  ('Todas as units são usadas por outra.', 'Every unit is used by another one.', 'Chaque unité est utilisée par une autre.', 'Jede Unit wird von einer anderen verwendet.'),
  ('Units de fora mais usadas', 'Most used outside units', 'Unités externes les plus utilisées', 'Am häufigsten verwendete externe Units'),
  ('Todas as units', 'All units', 'Toutes les unités', 'Alle Units'),
  ('Instabilidade', 'Instability', 'Instabilité', 'Instabilität'),
  ('usa %d · usada por %d', 'uses %d · used by %d', 'utilise %d · utilisée par %d', 'verwendet %d · verwendet von %d'),
  ('Clique numa unit para realçar o que ela usa (verde) e o que a usa (azul). Linhas a tracejado: só na implementation; a vermelho: ciclos.', 'Click a unit to highlight what it uses (green) and what uses it (blue). Dashed lines: implementation only; red: cycles.', 
      'Cliquez sur une unité pour mettre en évidence ce qu''elle utilise (vert) et ce qui l''utilise (bleu). Lignes en pointillés : uniquement dans l''implementation ; ro'
    + 'uge : cycles.', 'Klicken Sie auf eine Unit, um hervorzuheben, was sie verwendet (grün) und was sie verwendet (blau). Gestrichelte Linien: nur in der Implementation; rot: Zyklen.'),
  ('Filtrar por unit ou camada…', 'Filter by unit or layer…', 'Filtrer par unité ou couche…', 'Nach Unit oder Schicht filtern…'),
  ('ciclo', 'cycle', 'cycle', 'Zyklus'),
  ('-dependencias', '-dependencies', '-dependances', '-abhaengigkeiten'),
  ('%d métodos · %d linhas · complexidade máx. %d', '%d methods · %d lines · max. complexity %d', '%d méthodes · %d lignes · complexité max. %d', '%d Methoden · %d Zeilen · max. Komplexität %d'),
  ('Resumo', 'Summary', 'Résumé', 'Zusammenfassung'),
  ('Unit selecionada', 'Selected unit', 'Unité sélectionnée', 'Ausgewählte Unit'),
  ('Relatório de dependências', 'Dependency report', 'Rapport de dépendances', 'Abhängigkeitsbericht'),
  ('HTML (com mapa)', 'HTML (with map)', 'HTML (avec carte)', 'HTML (mit Karte)'),
  ('Analise um projeto para ver o mapa de dependências.', 'Analyze a project to see the dependency map.', 'Analysez un projet pour voir la carte des dépendances.', 'Analysieren Sie ein Projekt, um die Abhängigkeitskarte zu sehen.'),
  ('Ajustar', 'Fit', 'Ajuster', 'Anpassen'),
  ('Filtrar por unit ou camada…   ( / )', 'Filter by unit or layer…   ( / )', 'Filtrer par unité ou couche…   ( / )', 'Nach Unit oder Schicht filtern…   ( / )'),
  ('A calcular as dependências…', 'Calculating the dependencies…', 'Calcul des dépendances…', 'Abhängigkeiten werden berechnet…'),
  ('Não foi possível calcular as dependências: ', 'Could not calculate the dependencies: ', 'Impossible de calculer les dépendances : ', 'Die Abhängigkeiten konnten nicht berechnet werden: '),
  ('Este projeto não tem units para mostrar.', 'This project has no units to show.', 'Ce projet n''a pas d''unités à afficher.', 'Dieses Projekt hat keine Units zum Anzeigen.'),
  ('… e mais %d (veja o relatório)', '… and %d more (see the report)', '… et %d de plus (voir le rapport)', '… und %d weitere (siehe Bericht)'),
  ('Clique numa unit do mapa para ver os detalhes.', 'Click a unit on the map to see its details.', 'Cliquez sur une unité de la carte pour voir ses détails.', 'Klicken Sie auf eine Unit in der Karte, um Details zu sehen.'),
  ('Aguarde: o mapa de dependências ainda não está pronto.', 'Please wait: the dependency map is not ready yet.', 'Veuillez patienter : la carte des dépendances n''est pas encore prête.', 'Bitte warten: Die Abhängigkeitskarte ist noch nicht fertig.'),
  ('Simplificar', 'Simplify', 'Simplifier', 'Vereinfachen'),
  ('Esconde as ligações para as units usadas por muitas outras (voltam a aparecer ao selecionar uma unit).', 'Hides the links to units used by many others (they reappear when you select a unit).', 'Masque les liens vers les unités utilisées par beaucoup d''autres (ils réapparaissent à la sélection d''une unité).', 'Blendet die Verknüpfungen zu Units aus, die von vielen anderen verwendet werden (sie erscheinen wieder, wenn Sie eine Unit auswählen).'),
  ('Afastar', 'Zoom out', 'Dézoomer', 'Verkleinern'),
  ('Aproximar', 'Zoom in', 'Zoomer', 'Vergrößern'),
  ('Parâmetros', 'Parameters', 'Paramètres', 'Parameter'),
  ('Aninhamento', 'Nesting', 'Imbrication', 'Verschachtelung'),
  ('sem parâmetros', 'no parameters', 'sans paramètres', 'keine Parameter'),
  ('1 parâmetro', '1 parameter', '1 paramètre', '1 Parameter'),
  ('%d parâmetros', '%d parameters', '%d paramètres', '%d Parameter'),
  ('aninhamento %d', 'nesting %d', 'imbrication %d', 'Verschachtelung %d'),
  ('Código', 'Code', 'Code', 'Code'),
  ('Código-fonte', 'Source code', 'Code source', 'Quellcode'),
  ('Sem código para mostrar.', 'No code to show.', 'Aucun code à afficher.', 'Kein Code zum Anzeigen.'),
  ('Dê um duplo clique numa unit do Grafo, ou num ficheiro ou método do Mapa ou da Checklist, para ler o código aqui.', 'Double-click a unit in the Graph, or a file or method in the Map or the Checklist, to read its code here.', 'Double-cliquez sur une unité du graphe, ou sur un fichier ou une méthode de la carte ou de la checklist, pour lire son code ici.', 'Doppelklicken Sie im Graphen auf eine Unit oder in der Karte oder Checkliste auf eine Datei oder Methode, um den Code hier zu lesen.'),
  ('Copiar tudo', 'Copy all', 'Tout copier', 'Alles kopieren'),
  ('Fechar', 'Close', 'Fermer', 'Schließen'),
  ('Fechar todos', 'Close all', 'Tout fermer', 'Alle schließen'),
  ('Este ficheiro ainda não existe no código.', 'This file does not exist in the code yet.', 'Ce fichier n''existe pas encore dans le code.', 'Diese Datei existiert im Code noch nicht.'),
  ('Não foi possível ler o ficheiro: ', 'Could not read the file: ', 'Impossible de lire le fichier : ', 'Die Datei konnte nicht gelesen werden: '),
  ('Não foi possível localizar o método no ficheiro.', 'Could not locate the method in the file.', 'Impossible de localiser la méthode dans le fichier.', 'Die Methode wurde in der Datei nicht gefunden.'),
  ('Nenhum ficheiro aberto.', 'No file open.', 'Aucun fichier ouvert.', 'Keine Datei geöffnet.'),
  ('Código copiado', 'Code copied', 'Code copié', 'Code kopiert'),
  ('só de leitura', 'read-only', 'lecture seule', 'nur lesen'),
  ('linha', 'line', 'ligne', 'Zeile'),
  ('linhas', 'lines', 'lignes', 'Zeilen'),
  ('Ligaduras', 'Ligatures', 'Ligatures', 'Ligaturen'),
  ('Muda a fonte do código (as fontes modernas instaladas).', 'Changes the code font (the modern fonts installed).', 'Change la police du code (les polices modernes installées).', 'Ändert die Codeschrift (die installierten modernen Schriften).'),
  ('Mostra os operadores como -> => <> := fundidos (ligaduras da fonte).', 'Shows operators such as -> => <> := joined together (font ligatures).', 'Affiche les opérateurs comme -> => <> := fusionnés (ligatures de la police).', 'Zeigt Operatoren wie -> => <> := verbunden an (Schriftligaturen).'),
  ('Só há uma fonte de código instalada.', 'Only one code font is installed.', 'Une seule police de code est installée.', 'Es ist nur eine Codeschrift installiert.'),
  ('Linhas de código', 'Lines of code', 'Lignes de code', 'Codezeilen'),
  ('Cobertura de testes', 'Test coverage', 'Couverture des tests', 'Testabdeckung'),
  ('Duplicação', 'Duplication', 'Duplication', 'Duplizierung'),
  ('Dívida técnica', 'Technical debt', 'Dette technique', 'Technische Schulden'),
  ('Bugs', 'Bugs', 'Bugs', 'Bugs'),
  ('Vulnerabilidades', 'Vulnerabilities', 'Vulnérabilités', 'Schwachstellen'),
  ('Code smells', 'Code smells', 'Code smells', 'Code Smells'),
  ('Security hotspots', 'Security hotspots', 'Security hotspots', 'Security Hotspots'),
  ('Fiabilidade', 'Reliability', 'Fiabilité', 'Zuverlässigkeit'),
  ('Segurança', 'Security', 'Sécurité', 'Sicherheit'),
  ('Manutenção', 'Maintainability', 'Maintenabilité', 'Wartbarkeit'),
  ('Revisão de hotspots', 'Hotspots review', 'Revue des hotspots', 'Hotspot-Prüfung'),
  ('cobertura ', 'coverage ', 'couverture ', 'Abdeckung '),
  ('duplicação ', 'duplication ', 'duplication ', 'Duplizierung '),
  ('dívida ', 'debt ', 'dette ', 'Schulden '),
  ('complexidade cognitiva ', 'cognitive complexity ', 'complexité cognitive ', 'kognitive Komplexität '),
  ('VULN.', 'VULN.', 'VULN.', 'SCHW.'),
  ('PROBLEMA', 'ISSUE', 'PROBLÈME', 'PROBLEM'),
  ('risco ', 'risk ', 'risque ', 'Risiko '),
  ('Sem problemas abertos neste ficheiro.', 'No open issues in this file.', 'Aucun problème ouvert dans ce fichier.', 'Keine offenen Probleme in dieser Datei.'),
  ('problema', 'issue', 'problème', 'Problem'),
  ('problemas', 'issues', 'problèmes', 'Probleme'),
  ('hotspot', 'hotspot', 'hotspot', 'Hotspot'),
  ('hotspots', 'hotspots', 'hotspots', 'Hotspots'),
  ('segundo o SonarQube', 'according to SonarQube', 'selon SonarQube', 'laut SonarQube'),
  ('o SonarQube não tem cobertura', 'SonarQube has no coverage data', 'SonarQube n''a pas de couverture', 'SonarQube hat keine Abdeckungsdaten'),
  ('de linhas duplicadas', 'of duplicated lines', 'de lignes dupliquées', 'duplizierte Zeilen'),
  ('manutenção ', 'maintainability ', 'maintenabilité ', 'Wartbarkeit '),
  ('%d bugs · %d vulnerab. · %d smells', '%d bugs · %d vulnerab. · %d smells', '%d bugs · %d vulnérab. · %d smells', '%d Bugs · %d Schwachst. · %d Smells'),
  ('Dívida técnica por camada', 'Technical debt by layer', 'Dette technique par couche', 'Technische Schulden pro Schicht'),
  ('Horas estimadas pelo SonarQube', 'Hours estimated by SonarQube', 'Heures estimées par SonarQube', 'Von SonarQube geschätzte Stunden'),
  ('Horas', 'Hours', 'Heures', 'Stunden'),
  ('Ficheiros com mais dívida técnica', 'Files with the most technical debt', 'Fichiers avec le plus de dette technique', 'Dateien mit den meisten technischen Schulden'),
  ('Os %d com mais horas de dívida', 'The %d with the most hours of debt', 'Les %d avec le plus d''heures de dette', 'Die %d mit den meisten Schuldenstunden'),
  ('Revisão atual', 'Current revision', 'Révision actuelle', 'Aktuelle Revision'),
  ('Aspeto', 'Appearance', 'Apparence', 'Aussehen'),
  ('Aspeto atualizado', 'Appearance updated', 'Apparence mise à jour', 'Aussehen aktualisiert'),
  ('Cor de destaque, fontes e tamanho do texto. As escolhas são só tuas.', 'Accent colour, fonts and text size. The choices are only yours.', 'Couleur d''accentuation, polices et taille du texte. Les choix ne sont qu''à vous.', 'Akzentfarbe, Schriften und Textgröße. Die Auswahl gilt nur für Sie.'),
  ('Repor aspeto padrão', 'Reset appearance', 'Rétablir l''apparence', 'Aussehen zurücksetzen'),
  ('Cor de destaque', 'Accent colour', 'Couleur d''accentuation', 'Akzentfarbe'),
  ('A cor dos botões, dos itens selecionados e dos gráficos. As variantes forte e suave, e o texto por cima, calculam-se sozinhas para se lerem bem nos dois temas.', 
      'The colour of buttons, selected items and charts. The strong and soft variants, and the text on top, are calculated automatically so they read well in both them'
    + 'es.', 
      'La couleur des boutons, des éléments sélectionnés et des graphiques. Les variantes forte et douce, et le texte dessus, se calculent seules pour rester lisibles '
    + 'dans les deux thèmes.', 
      'Die Farbe von Schaltflächen, ausgewählten Elementen und Diagrammen. Die kräftige und die sanfte Variante sowie der Text darauf werden automatisch berechnet, dam'
    + 'it sie in beiden Designs gut lesbar sind.'),
  ('Ou uma cor livre (#RRGGBB)', 'Or a free colour (#RRGGBB)', 'Ou une couleur libre (#RRGGBB)', 'Oder eine freie Farbe (#RRGGBB)'),
  ('Fontes', 'Fonts', 'Polices', 'Schriften'),
  ('Interface', 'Interface', 'Interface', 'Oberfläche'),
  ('Texto técnico (nomes, números, etiquetas)', 'Technical text (names, numbers, labels)', 'Texte technique (noms, nombres, étiquettes)', 'Technischer Text (Namen, Zahlen, Etiketten)'),
  ('Código (página Código)', 'Code (Code page)', 'Code (page Code)', 'Code (Seite Code)'),
  ('Tamanho', 'Size', 'Taille', 'Größe'),
  ('Texto da aplicação', 'Application text', 'Texte de l''application', 'Anwendungstext'),
  ('Código (em pontos)', 'Code (in points)', 'Code (en points)', 'Code (in Punkt)'),
  ('Pré-visualização', 'Preview', 'Aperçu', 'Vorschau'),
  ('Automática', 'Automatic', 'Automatique', 'Automatisch'),
  ('Automático', 'Automatic', 'Automatique', 'Automatisch'),
  ('Verde', 'Green', 'Vert', 'Grün'),
  ('Azul', 'Blue', 'Bleu', 'Blau'),
  ('Indigo', 'Indigo', 'Indigo', 'Indigo'),
  ('Violeta', 'Violet', 'Violet', 'Violett'),
  ('Rosa', 'Pink', 'Rose', 'Rosa'),
  ('Vermelho', 'Red', 'Rouge', 'Rot'),
  ('Laranja', 'Orange', 'Orange', 'Orange'),
  ('Grafite', 'Graphite', 'Graphite', 'Graphit'),
  ('Acerca', 'About', 'À propos', 'Über'),
  ('Acerca do CodeManager', 'About CodeManager', 'À propos de CodeManager', 'Über CodeManager'),
  ('A versão, o sistema e as ligações úteis.', 'The version, the system and useful links.', 'La version, le système et des liens utiles.', 'Die Version, das System und nützliche Links.'),
  ('Mapa e checklist do código-fonte Delphi', 'Delphi source code map and checklist', 'Carte et checklist du code source Delphi', 'Karte und Checkliste für Delphi-Quellcode'),
  ('Versão ', 'Version ', 'Version ', 'Version '),
  ('Versão', 'Version', 'Version', 'Version'),
  ('Informação', 'Information', 'Informations', 'Informationen'),
  ('Compilação', 'Build', 'Compilation', 'Build'),
  ('Compilado em', 'Built on', 'Compilé le', 'Erstellt am'),
  ('Compilador', 'Compiler', 'Compilateur', 'Compiler'),
  ('Sistema', 'System', 'Système', 'System'),
  ('Git', 'Git', 'Git', 'Git'),
  ('Subversion', 'Subversion', 'Subversion', 'Subversion'),
  ('Mercurial', 'Mercurial', 'Mercurial', 'Mercurial'),
  ('disponível', 'available', 'disponible', 'verfügbar'),
  ('não encontrado', 'not found', 'introuvable', 'nicht gefunden'),
  ('Pasta de dados', 'Data folder', 'Dossier de données', 'Datenordner'),
  ('Licença', 'License', 'Licence', 'Lizenz'),
  ('Repositório', 'Repository', 'Dépôt', 'Repository'),
  ('Novidades', 'What''s new', 'Nouveautés', 'Neuigkeiten'),
  ('Reportar um problema', 'Report a problem', 'Signaler un problème', 'Problem melden'),
  ('Copiar informação', 'Copy information', 'Copier les informations', 'Informationen kopieren'),
  ('Informação copiada', 'Information copied', 'Informations copiées', 'Informationen kopiert'),
  ('Licença e créditos', 'License and credits', 'Licence et crédits', 'Lizenz und Danksagungen'),
  ('Distribuído sob a licença MIT. © 2026 João Ferreira.', 'Distributed under the MIT license. © 2026 João Ferreira.', 'Distribué sous licence MIT. © 2026 João Ferreira.', 'Unter der MIT-Lizenz veröffentlicht. © 2026 João Ferreira.'),
  ('Gráficos do Painel: Chart4D (MIT, GDK Software).', 'Dashboard charts: Chart4D (MIT, GDK Software).', 'Graphiques du tableau de bord : Chart4D (MIT, GDK Software).', 'Diagramme der Übersicht: Chart4D (MIT, GDK Software).'),
  ('Testes: DUnitX (Apache 2.0).', 'Tests: DUnitX (Apache 2.0).', 'Tests : DUnitX (Apache 2.0).', 'Tests: DUnitX (Apache 2.0).'),
  ('Ícones: Material Design Icons (Apache 2.0).', 'Icons: Material Design Icons (Apache 2.0).', 'Icônes : Material Design Icons (Apache 2.0).', 'Symbole: Material Design Icons (Apache 2.0).'),
  ('Mapa de dependências inspirado no DelphiNodeEditor (MIT, HemulGM).', 'Dependency map inspired by DelphiNodeEditor (MIT, HemulGM).', 'Carte des dépendances inspirée de DelphiNodeEditor (MIT, HemulGM).', 'Abhängigkeitskarte angelehnt an DelphiNodeEditor (MIT, HemulGM).'),
  ('Os avisos completos estão em THIRD-PARTY-NOTICES.md, no repositório.', 'The full notices are in THIRD-PARTY-NOTICES.md, in the repository.', 'Les avis complets sont dans THIRD-PARTY-NOTICES.md, dans le dépôt.', 'Die vollständigen Hinweise stehen in THIRD-PARTY-NOTICES.md im Repository.'),
  ('Lista de materiais de software (SBOM)', 'Software bill of materials (SBOM)', 'Nomenclature logicielle (SBOM)', 'Software-Stückliste (SBOM)'),
  ('Componentes', 'Components', 'Composants', 'Komponenten'),
  ('Com ficheiro encontrado', 'With file found', 'Avec fichier trouvé', 'Mit gefundener Datei'),
  ('Da Embarcadero', 'From Embarcadero', 'D''Embarcadero', 'Von Embarcadero'),
  ('De terceiros', 'Third-party', 'Tiers', 'Von Drittanbietern'),
  ('Do projeto', 'From the project', 'Du projet', 'Aus dem Projekt'),
  ('Por confirmar', 'Unconfirmed', 'Non confirmés', 'Unbestätigt'),
  ('Campo', 'Field', 'Champ', 'Feld'),
  ('Valor', 'Value', 'Valeur', 'Wert'),
  ('Nome', 'Name', 'Nom', 'Name'),
  ('Empresa', 'Company', 'Société', 'Firma'),
  ('Descrição', 'Description', 'Description', 'Beschreibung'),
  ('Plataforma', 'Platform', 'Plateforme', 'Plattform'),
  ('Configuração de compilação', 'Build configuration', 'Configuration de build', 'Build-Konfiguration'),
  ('Mapa de ligação', 'Link map', 'Fichier map', 'Link-Map'),
  ('Resumo por origem', 'Summary by origin', 'Résumé par origine', 'Zusammenfassung nach Herkunft'),
  ('Origem', 'Origin', 'Origine', 'Herkunft'),
  ('Evidência', 'Evidence', 'Preuve', 'Nachweis'),
  ('Confiança', 'Confidence', 'Confiance', 'Vertrauen'),
  ('Pontos de atenção', 'Points of attention', 'Points d''attention', 'Hinweise'),
  ('Projeto local', 'Local project', 'Projet local', 'Lokales Projekt'),
  ('RTL da Embarcadero', 'Embarcadero RTL', 'RTL d''Embarcadero', 'Embarcadero-RTL'),
  ('VCL da Embarcadero', 'Embarcadero VCL', 'VCL d''Embarcadero', 'Embarcadero-VCL'),
  ('FMX da Embarcadero', 'Embarcadero FMX', 'FMX d''Embarcadero', 'Embarcadero-FMX'),
  ('Terceiros', 'Third party', 'Tiers', 'Drittanbieter'),
  ('Forte', 'Strong', 'Forte', 'Hoch'),
  ('Média', 'Medium', 'Moyenne', 'Mittel'),
  ('Fraca', 'Weak', 'Faible', 'Niedrig'),
  ('Cláusula uses', 'Uses clause', 'Clause uses', 'Uses-Klausel'),
  ('Filtrar por unit ou origem…', 'Filter by unit or origin…', 'Filtrer par unité ou origine…', 'Nach Unit oder Herkunft filtern…'),
  ('-sbom-relatorio', '-sbom-report', '-sbom-rapport', '-sbom-bericht'),
  ('Nada a assinalar: todos os componentes foram confirmados.', 'Nothing to flag: every component has been confirmed.', 'Rien à signaler : tous les composants sont confirmés.', 'Nichts zu beanstanden: Alle Komponenten wurden bestätigt.'),
  ('Units de terceiros sem ficheiro encontrado: só se conhecem pelo nome. Acrescenta as pastas das bibliotecas aos caminhos de procura do projeto para as confirmar.', 'Third-party units with no file found: they are only known by name. Add the library folders to the project search paths to confirm them.', 
      'Unités tierces sans fichier trouvé : on ne les connaît que par leur nom. Ajoute les dossiers des bibliothèques aux chemins de recherche du projet pour les confi'
    + 'rmer.', 
      'Drittanbieter-Units ohne gefundene Datei: Sie sind nur dem Namen nach bekannt. Füge die Bibliotheksordner zu den Suchpfaden des Projekts hinzu, um sie zu bestät'
    + 'igen.'),
  ('Como ler este relatório', 'How to read this report', 'Comment lire ce rapport', 'So lesen Sie diesen Bericht'),
  ('Um SBOM lista o que entra no teu software: aqui, as units que o projeto usa e de onde vêm.', 'An SBOM lists what goes into your software: here, the units the project uses and where they come from.', 'Une SBOM liste ce qui entre dans ton logiciel : ici, les unités que le projet utilise et d''où elles viennent.', 'Eine SBOM listet auf, was in deiner Software steckt: hier die Units, die das Projekt verwendet, und woher sie stammen.'),
  (
      'Confiança forte: o ficheiro da unit foi encontrado (e tem hash SHA-256). Média: só se conhece pelo nome, mas é uma biblioteca da Embarcadero. Fraca: só se conhe'
    + 'ce pelo nome e não se sabe de onde vem.', 
      'Strong confidence: the unit file was found (and has a SHA-256 hash). Medium: it is only known by name, but it is an Embarcadero library. Weak: it is only known '
    + 'by name and where it comes from is unknown.', 
      'Confiance forte : le fichier de l''unité a été trouvé (et a un hash SHA-256). Moyenne : on ne la connaît que par son nom, mais c''est une bibliothèque d''Embarcade'
    + 'ro. Faible : on ne la connaît que par son nom et on ignore d''où elle vient.', 
      'Hohes Vertrauen: Die Datei der Unit wurde gefunden (und hat einen SHA-256-Hash). Mittel: Sie ist nur dem Namen nach bekannt, aber eine Embarcadero-Bibliothek. N'
    + 'iedrig: Sie ist nur dem Namen nach bekannt, ihre Herkunft ist unbekannt.'),
  (
      'O relatório vem da análise do código-fonte (cláusulas uses e .dproj), sem compilar: uma unit referenciada pode não ficar no executável. Com um ficheiro .map as '
    + 'units realmente ligadas ficam confirmadas.', 
      'The report comes from analysing the source code (uses clauses and .dproj), without compiling: a referenced unit may not end up in the executable. With a .map fi'
    + 'le, the units actually linked are confirmed.', 
      'Le rapport provient de l''analyse du code source (clauses uses et .dproj), sans compiler : une unité référencée peut ne pas finir dans l''exécutable. Avec un fich'
    + 'ier .map, les unités réellement liées sont confirmées.', 
      'Der Bericht stammt aus der Analyse des Quellcodes (Uses-Klauseln und .dproj), ohne zu kompilieren: Eine referenzierte Unit landet möglicherweise nicht in der au'
    + 'sführbaren Datei. Mit einer .map-Datei werden die tatsächlich gebundenen Units bestätigt.'),
  ('Fora do mapa', 'Not in the map', 'Hors de la map', 'Nicht in der Map'),
  ('Referenciadas no código mas ausentes do mapa de ligação (podem não ficar no executável):', 'Referenced in the code but missing from the link map (they may not end up in the executable):', 'Référencées dans le code mais absentes de la map de liaison (elles peuvent ne pas finir dans l''exécutable) :', 'Im Code referenziert, aber in der Link-Map nicht vorhanden (sie landen möglicherweise nicht in der ausführbaren Datei):'),
  ('SBOM', 'SBOM', 'SBOM', 'SBOM'),
  ('SBOM: lista de materiais de software', 'SBOM: software bill of materials', 'SBOM : nomenclature logicielle', 'SBOM: Software-Stückliste'),
  ('Filtrar por unit, origem ou licença…   ( / )', 'Filter by unit, origin or license…   ( / )', 'Filtrer par unité, origine ou licence…   ( / )', 'Nach Unit, Herkunft oder Lizenz filtern…   ( / )'),
  ('Opções', 'Options', 'Options', 'Optionen'),
  ('Incluir as units do projeto', 'Include the project units', 'Inclure les unités du projet', 'Units des Projekts einbeziehen'),
  ('Confirmar com o ficheiro .map', 'Confirm with the .map file', 'Confirmer avec le fichier .map', 'Mit der .map-Datei bestätigen'),
  ('Calcular os hashes SHA-256', 'Compute the SHA-256 hashes', 'Calculer les hashes SHA-256', 'SHA-256-Hashes berechnen'),
  ('Gerar de novo', 'Generate again', 'Générer à nouveau', 'Neu erzeugen'),
  ('CycloneDX (JSON)', 'CycloneDX (JSON)', 'CycloneDX (JSON)', 'CycloneDX (JSON)'),
  ('SPDX (JSON)', 'SPDX (JSON)', 'SPDX (JSON)', 'SPDX (JSON)'),
  ('Relatório HTML', 'HTML report', 'Rapport HTML', 'HTML-Bericht'),
  ('Analise um projeto para gerar o SBOM.', 'Analyse a project to generate the SBOM.', 'Analyse un projet pour générer la SBOM.', 'Analysiere ein Projekt, um die SBOM zu erzeugen.'),
  ('A gerar o SBOM…', 'Generating the SBOM…', 'Génération de la SBOM…', 'SBOM wird erzeugt…'),
  ('Não foi possível gerar o SBOM: ', 'Could not generate the SBOM: ', 'Impossible de générer la SBOM : ', 'Die SBOM konnte nicht erzeugt werden: '),
  ('Este projeto não tem componentes para mostrar.', 'This project has no components to show.', 'Ce projet n''a aucun composant à afficher.', 'Dieses Projekt hat keine Komponenten zum Anzeigen.'),
  ('Sem ficheiro encontrado', 'No file found', 'Aucun fichier trouvé', 'Keine Datei gefunden'),
  ('Aguarde: o SBOM ainda não está pronto.', 'Wait: the SBOM is not ready yet.', 'Patiente : la SBOM n''est pas encore prête.', 'Bitte warten: Die SBOM ist noch nicht fertig.'),
  ('Não se encontrou o ficheiro .dproj: a versão e os caminhos de procura ficam por preencher.', 'The .dproj file was not found: the version and the search paths stay empty.', 'Le fichier .dproj est introuvable : la version et les chemins de recherche restent vides.', 'Die .dproj-Datei wurde nicht gefunden: Version und Suchpfade bleiben leer.'),
  ('Não se encontrou a instalação do Delphi: as units da Embarcadero só se reconhecem pelo nome.', 'The Delphi installation was not found: Embarcadero units are only recognised by name.', 'L''installation de Delphi est introuvable : les unités d''Embarcadero ne sont reconnues que par leur nom.', 'Die Delphi-Installation wurde nicht gefunden: Embarcadero-Units werden nur am Namen erkannt.'),
  ('Não se encontrou o ficheiro .map: compila o projeto com o mapa «Detailed» para confirmar as units ligadas.', 'The .map file was not found: build the project with a "Detailed" map to confirm the linked units.', 'Le fichier .map est introuvable : compile le projet avec une map « Detailed » pour confirmer les unités liées.', 'Die .map-Datei wurde nicht gefunden: Kompiliere das Projekt mit einer „Detailed“-Map, um die gebundenen Units zu bestätigen.'),
  ('SBOM inspirado no DX.Comply (MIT, Olaf Monien).', 'SBOM inspired by DX.Comply (MIT, Olaf Monien).', 'SBOM inspirée de DX.Comply (MIT, Olaf Monien).', 'SBOM inspiriert von DX.Comply (MIT, Olaf Monien).'),
  ('classe', 'class', 'classe', 'Klasse'),
  ('interface', 'interface', 'interface', 'Schnittstelle'),
  ('objeto', 'object', 'objet', 'Objekt'),
  ('record', 'record', 'record', 'Record'),
  ('Profundidade', 'Depth', 'Profondeur', 'Tiefe'),
  ('Filhas', 'Children', 'Filles', 'Unterklassen'),
  ('Classes e herança', 'Classes and inheritance', 'Classes et héritage', 'Klassen und Vererbung'),
  ('Classes', 'Classes', 'Classes', 'Klassen'),
  ('Interfaces', 'Interfaces', 'Interfaces', 'Schnittstellen'),
  ('Records', 'Records', 'Records', 'Records'),
  ('Profundidade máxima', 'Maximum depth', 'Profondeur maximale', 'Maximale Tiefe'),
  ('Profundidade média', 'Average depth', 'Profondeur moyenne', 'Durchschnittliche Tiefe'),
  ('Com profundidade mínima (cadeia externa desconhecida)', 'With a minimum depth (unknown external chain)', 'Avec une profondeur minimale (chaîne externe inconnue)', 'Mit Mindesttiefe (unbekannte externe Kette)'),
  ('Classes mais profundas', 'Deepest classes', 'Classes les plus profondes', 'Tiefste Klassen'),
  ('Classes com mais filhas', 'Classes with the most children', 'Classes avec le plus de filles', 'Klassen mit den meisten Unterklassen'),
  ('Árvore de herança', 'Inheritance tree', 'Arbre d''héritage', 'Vererbungsbaum'),
  ('Um «>=» na profundidade quer dizer que a classe herda de uma classe de fora do projeto de que não se conhece a cadeia: a profundidade real é, pelo menos, essa.', 'A «>=» in the depth means the class inherits from a class outside the project whose chain is unknown: the real depth is at least that.', 
      'Un «>=» dans la profondeur signifie que la classe hérite d''une classe extérieure au projet dont la chaîne est inconnue : la profondeur réelle est au moins celle'
    + '-ci.', 
      'Ein «>=» bei der Tiefe bedeutet, dass die Klasse von einer Klasse außerhalb des Projekts erbt, deren Kette unbekannt ist: die tatsächliche Tiefe ist mindestens '
    + 'so groß.'),
  ('sim', 'yes', 'oui', 'ja'),
  ('não', 'no', 'non', 'nein'),
  ('Ancestral', 'Ancestor', 'Ancêtre', 'Vorfahre'),
  ('Exata', 'Exact', 'Exacte', 'Exakt'),
  ('Profundidade no projeto', 'Depth in the project', 'Profondeur dans le projet', 'Tiefe im Projekt'),
  ('Descendentes', 'Descendants', 'Descendants', 'Nachfahren'),
  ('Linha', 'Line', 'Ligne', 'Zeile'),
  ('Filtrar por classe, ancestral ou ficheiro…   ( / )', 'Filter by class, ancestor or file…   ( / )', 'Filtrer par classe, ancêtre ou fichier…   ( / )', 'Nach Klasse, Vorfahre oder Datei filtern…   ( / )'),
  ('Mostrar as interfaces', 'Show interfaces', 'Afficher les interfaces', 'Schnittstellen anzeigen'),
  ('Analise um projeto para ver as classes.', 'Analyse a project to see its classes.', 'Analysez un projet pour voir ses classes.', 'Analysieren Sie ein Projekt, um seine Klassen zu sehen.'),
  ('Este projeto não declara classes.', 'This project declares no classes.', 'Ce projet ne déclare aucune classe.', 'Dieses Projekt deklariert keine Klassen.'),
  ('Com profundidade mínima', 'With a minimum depth', 'Avec une profondeur minimale', 'Mit Mindesttiefe'),
  ('Duplo clique numa classe abre o código na sua declaração. Os títulos ordenam a lista.', 'Double-click a class to open the code at its declaration. The headings sort the list.', 'Double-cliquez sur une classe pour ouvrir le code à sa déclaration. Les titres trient la liste.', 'Doppelklick auf eine Klasse öffnet den Code an ihrer Deklaration. Die Überschriften sortieren die Liste.'),
  ('As %d com maior profundidade de herança', 'The %d with the deepest inheritance', 'Les %d à la plus grande profondeur d’héritage', 'Die %d mit der größten Vererbungstiefe'),
  ('Profundidade de herança', 'Inheritance depth', 'Profondeur d''héritage', 'Vererbungstiefe'),
  ('Quantas classes em cada profundidade (1 = sem ancestral do projeto)', 'How many classes at each depth (1 = no ancestor in the project)', 'Combien de classes à chaque profondeur (1 = sans ancêtre dans le projet)', 'Wie viele Klassen in jeder Tiefe (1 = ohne Vorfahre im Projekt)'),
  ('Biblioteca', 'Library', 'Bibliothèque', 'Bibliothek'),
  ('Ver', 'See', 'Voir', 'Siehe'),
  ('Com licença conhecida', 'With a known license', 'Avec licence connue', 'Mit bekannter Lizenz'),
  ('Sem licença conhecida', 'Without a known license', 'Sans licence connue', 'Ohne bekannte Lizenz'),
  ('Units de terceiros sem licença reconhecida: confirma a licença da biblioteca antes de distribuir o programa.', 'Third-party units without a recognised license: check the library license before distributing the program.', 'Unités tierces sans licence reconnue : vérifiez la licence de la bibliothèque avant de distribuer le programme.', 'Drittanbieter-Units ohne erkannte Lizenz: Prüfen Sie die Lizenz der Bibliothek, bevor Sie das Programm weitergeben.'),
  (
      'A biblioteca, a versão e a licença das units de terceiros vêm do boss.json, do boss-lock.json, do nome da pasta do GetIt e do ficheiro de licença da pasta da bi'
    + 'blioteca; uma licença só aparece quando o texto a justifica.', 
      'The library, version and license of third-party units come from boss.json, boss-lock.json, the GetIt folder name and the license file in the library folder; a l'
    + 'icense only appears when the text justifies it.', 
      'La bibliothèque, la version et la licence des unités tierces viennent de boss.json, de boss-lock.json, du nom du dossier GetIt et du fichier de licence du dossi'
    + 'er de la bibliothèque ; une licence n’apparaît que si le texte la justifie.', 
      'Bibliothek, Version und Lizenz der Drittanbieter-Units stammen aus boss.json, boss-lock.json, dem GetIt-Ordnernamen und der Lizenzdatei im Bibliotheksordner; ei'
    + 'ne Lizenz erscheint nur, wenn der Text sie belegt.')
  );

  // trocos dos modelos HTML (res/templates), por ordem de leitura
  HtmlRows: array[0..84] of array[0..3] of string = (
  ('lang="pt-PT"', 'lang="en"', 'lang="fr"', 'lang="de"'),
  (' — Mapa de Código-Fonte</title>', ' — Source Code Map</title>', ' — Carte du code source</title>', ' — Quellcode-Karte</title>'),
  ('<span class="eyebrow">Mapa de código-fonte</span>', '<span class="eyebrow">Source code map</span>', '<span class="eyebrow">Carte du code source</span>', '<span class="eyebrow">Quellcode-Karte</span>'),
  (
      'Estrutura de pastas, ficheiros por pasta e métodos de cada unit — vista gerada por análise estática do código-fonte, com checkboxes de Compila/Sonar guardadas n'
    + 'este navegador.', 
      'Folder structure, files per folder and the methods of each unit — a view generated by static analysis of the source code, with Builds/Sonar checkboxes saved in '
    + 'this browser.', 
      'Structure des dossiers, fichiers par dossier et méthodes de chaque unité — vue générée par analyse statique du code source, avec des cases Compile/Sonar enregis'
    + 'trées dans ce navigateur.', 
      'Ordnerstruktur, Dateien pro Ordner und Methoden jeder Unit — Ansicht aus der statischen Analyse des Quellcodes, mit Kompiliert/Sonar-Kontrollkästchen, die in di'
    + 'esem Browser gespeichert werden.'),
  ('gerado __GENERATED_DATE__', 'generated __GENERATED_DATE__', 'généré le __GENERATED_DATE__', 'erstellt __GENERATED_DATE__'),
  ('<span>Pastas</span>', '<span>Folders</span>', '<span>Dossiers</span>', '<span>Ordner</span>'),
  ('<span>Ficheiros</span>', '<span>Files</span>', '<span>Fichiers</span>', '<span>Dateien</span>'),
  ('<span>Métodos</span>', '<span>Methods</span>', '<span>Méthodes</span>', '<span>Methoden</span>'),
  ('<span>Units com métodos</span>', '<span>Units with methods</span>', '<span>Unités avec méthodes</span>', '<span>Units mit Methoden</span>'),
  ('<span>Ficheiros · Compila</span>', '<span>Files · Builds</span>', '<span>Fichiers · Compile</span>', '<span>Dateien · Kompiliert</span>'),
  ('<span>Ficheiros · Sonar</span>', '<span>Files · Sonar</span>', '<span>Fichiers · Sonar</span>', '<span>Dateien · Sonar</span>'),
  ('<span>Métodos · Compila</span>', '<span>Methods · Builds</span>', '<span>Méthodes · Compile</span>', '<span>Methoden · Kompiliert</span>'),
  ('<span>Métodos · Sonar</span>', '<span>Methods · Sonar</span>', '<span>Méthodes · Sonar</span>', '<span>Methoden · Sonar</span>'),
  ('🖨️ Imprimir (boa qualidade)', '🖨️ Print (high quality)', '🖨️ Imprimer (haute qualité)', '🖨️ Drucken (hohe Qualität)'),
  ('>Expandir tudo<', '>Expand all<', '>Tout développer<', '>Alle aufklappen<'),
  ('>Colapsar tudo<', '>Collapse all<', '>Tout réduire<', '>Alle zuklappen<'),
  ('>Expandir métodos<', '>Expand methods<', '>Développer les méthodes<', '>Methoden aufklappen<'),
  ('>Colapsar métodos<', '>Collapse methods<', '>Réduire les méthodes<', '>Methoden zuklappen<'),
  ('title="Alternar tema"', 'title="Toggle theme"', 'title="Changer de thème"', 'title="Design wechseln"'),
  ('placeholder="Filtrar por pasta, ficheiro ou método…"', 'placeholder="Filter by folder, file or method…"', 'placeholder="Filtrer par dossier, fichier ou méthode…"', 'placeholder="Nach Ordner, Datei oder Methode filtern…"'),
  ('title="Expande tudo e imprime o mapa completo"', 'title="Expands everything and prints the full map"', 'title="Développe tout et imprime la carte complète"', 'title="Klappt alles auf und druckt die vollständige Karte"'),
  (
      'Os métodos de cada unit são extraídos automaticamente das declarações <code>function</code>/<code>procedure</code>/<code>constructor</code>/<code>destructor</co'
    + 'de>. É uma heurística de análise estática, não um parser Delphi completo — units sem métodos declarados (DTOs, modelos simples, exceções, tipos) não mostram o c'
    + 'ontador.', 
      'The methods of each unit are extracted automatically from the <code>function</code>/<code>procedure</code>/<code>constructor</code>/<code>destructor</code> decl'
    + 'arations. This is a static-analysis heuristic, not a full Delphi parser — units without declared methods (DTOs, simple models, exceptions, types) do not show th'
    + 'e counter.', 
      'Les méthodes de chaque unité sont extraites automatiquement des déclarations <code>function</code>/<code>procedure</code>/<code>constructor</code>/<code>destruc'
    + 'tor</code>. C''est une heuristique d''analyse statique, pas un analyseur Delphi complet — les unités sans méthodes déclarées (DTO, modèles simples, exceptions, ty'
    + 'pes) n''affichent pas le compteur.', 
      'Die Methoden jeder Unit werden automatisch aus den Deklarationen <code>function</code>/<code>procedure</code>/<code>constructor</code>/<code>destructor</code> e'
    + 'xtrahiert. Das ist eine Heuristik der statischen Analyse, kein vollständiger Delphi-Parser — Units ohne deklarierte Methoden (DTOs, einfache Modelle, Exceptions'
    + ', Typen) zeigen den Zähler nicht an.'),
  (
      'As checkboxes <strong>C</strong> (Compila) e <strong>S</strong> (Sonar) junto a cada unit e método ficam guardadas no navegador (localStorage) e sobrevivem a no'
    + 'vas gerações desta página no mesmo browser — ao contrário da estrutura de pastas/ficheiros/métodos, que é sempre recalculada.', 
      'The <strong>C</strong> (Builds) and <strong>S</strong> (Sonar) checkboxes next to each unit and method are saved in the browser (localStorage) and survive new g'
    + 'enerations of this page in the same browser — unlike the folder/file/method structure, which is always recalculated.', 
      'Les cases <strong>C</strong> (Compile) et <strong>S</strong> (Sonar) à côté de chaque unité et méthode sont enregistrées dans le navigateur (localStorage) et su'
    + 'rvivent aux nouvelles générations de cette page dans le même navigateur — contrairement à la structure dossiers/fichiers/méthodes, toujours recalculée.', 
      'Die Kontrollkästchen <strong>C</strong> (Kompiliert) und <strong>S</strong> (Sonar) neben jeder Unit und Methode werden im Browser (localStorage) gespeichert un'
    + 'd überstehen neue Erzeugungen dieser Seite im selben Browser — anders als die Struktur aus Ordnern/Dateien/Methoden, die immer neu berechnet wird.'),
  ('"Compila sem erros"', '"Builds without errors"', '"Compile sans erreur"', '"Kompiliert fehlerfrei"'),
  ('"SonarQube aprovado"', '"Approved in SonarQube"', '"Approuvé dans SonarQube"', '"In SonarQube freigegeben"'),
  ('"Método compila sem erros"', '"Method builds without errors"', '"La méthode compile sans erreur"', '"Methode kompiliert fehlerfrei"'),
  ('"Método aprovado no SonarQube"', '"Method approved in SonarQube"', '"Méthode approuvée dans SonarQube"', '"Methode in SonarQube freigegeben"'),
  ('(mlist.length === 1 ? " método" : " métodos")', '(mlist.length === 1 ? " method" : " methods")', '(mlist.length === 1 ? " méthode" : " méthodes")', '(mlist.length === 1 ? " Methode" : " Methoden")'),
  ('" ficheiro" + (counts.files === 1 ? "" : "s")', '" file" + (counts.files === 1 ? "" : "s")', '" fichier" + (counts.files === 1 ? "" : "s")', '" Datei" + (counts.files === 1 ? "" : "en")'),
  ('" ficheiro(s) · "', '" file(s) · "', '" fichier(s) · "', '" Datei(en) · "'),
  ('" método(s)"', '" method(s)"', '" méthode(s)"', '" Methode(n)"'),
  ('"Ficheiros: "', '"Files: "', '"Fichiers : "', '"Dateien: "'),
  ('" compila &middot; "', '" builds &middot; "', '" compile &middot; "', '" kompiliert &middot; "'),
  ('" — Métodos: "', '" — Methods: "', '" — Méthodes : "', '" — Methoden: "'),
  ('"<br>impresso em "', '"<br>printed on "', '"<br>imprimé le "', '"<br>gedruckt am "'),
  ('"Nenhum resultado para esta pesquisa."', '"No results for this search."', '"Aucun résultat pour cette recherche."', '"Keine Ergebnisse für diese Suche."'),
  (' — Checklist de Código-Fonte</title>', ' — Source Code Checklist</title>', ' — Checklist du code source</title>', ' — Quellcode-Checkliste</title>'),
  ('<span class="eyebrow">Código-fonte próprio</span>', '<span class="eyebrow">Own source code</span>', '<span class="eyebrow">Code source propre</span>', '<span class="eyebrow">Eigener Quellcode</span>'),
  ('Checklist de Código-Fonte — __PROJECT_NAME__</h1>', 'Source Code Checklist — __PROJECT_NAME__</h1>', 'Checklist du code source — __PROJECT_NAME__</h1>', 'Quellcode-Checkliste — __PROJECT_NAME__</h1>'),
  (
      'Marca cada unidade como revista/concluída, marca prioridades e anota notas — e dentro de cada unidade, revê método a método. Tudo fica guardado neste navegador '
    + '— ficheiro 100% offline, sem servidor.', 
      'Mark each unit as reviewed/done, set priorities and add notes — and inside each unit, review method by method. Everything is saved in this browser — a 100% offl'
    + 'ine file, no server.', 
      'Marquez chaque unité comme revue/terminée, définissez des priorités et ajoutez des notes — et, dans chaque unité, revoyez méthode par méthode. Tout est enregist'
    + 'ré dans ce navigateur — fichier 100 % hors ligne, sans serveur.', 
      'Markieren Sie jede Unit als geprüft/erledigt, setzen Sie Prioritäten und notieren Sie Anmerkungen — und prüfen Sie innerhalb jeder Unit Methode für Methode. All'
    + 'es wird in diesem Browser gespeichert — eine 100 % Offline-Datei, ohne Server.'),
  ('placeholder="Filtrar por nome ou pasta…"', 'placeholder="Filter by name or folder…"', 'placeholder="Filtrer par nom ou dossier…"', 'placeholder="Nach Name oder Ordner filtern…"'),
  ('<div class="progress-label">concluído</div>', '<div class="progress-label">done</div>', '<div class="progress-label">terminé</div>', '<div class="progress-label">erledigt</div>'),
  ('0 / 0 ficheiros</div>', '0 / 0 files</div>', '0 / 0 fichiers</div>', '0 / 0 Dateien</div>'),
  (' mostrar só marcados com ★', ' show only starred ★', ' afficher seulement les ★', ' nur mit ★ markierte anzeigen'),
  ('title="Limpa filtros activos e imprime a checklist completa, com todas as secções e métodos expandidos"', 'title="Clears the active filters and prints the full checklist, with all sections and methods expanded"', 'title="Efface les filtres actifs et imprime la checklist complète, avec toutes les sections et méthodes développées"', 'title="Löscht die aktiven Filter und druckt die vollständige Checkliste mit allen aufgeklappten Abschnitten und Methoden"'),
  ('>Exportar progresso<', '>Export progress<', '>Exporter la progression<', '>Fortschritt exportieren<'),
  ('>Importar<', '>Import<', '>Importer<', '>Importieren<'),
  ('>Copiar Markdown<', '>Copy Markdown<', '>Copier le Markdown<', '>Markdown kopieren<'),
  ('>Reiniciar<', '>Reset<', '>Réinitialiser<', '>Zurücksetzen<'),
  ('aria-label="Ir para pasta"', 'aria-label="Go to folder"', 'aria-label="Aller au dossier"', 'aria-label="Zum Ordner springen"'),
  (
      'A checklist de métodos (botão com contador junto a cada ficheiro) é extraída automaticamente das declarações <code>function</code>/<code>procedure</code>/<code>'
    + 'constructor</code>/<code>destructor</code> de cada unit. É uma heurística de análise estática, não um parser Delphi completo — units sem métodos declarados (DTO'
    + 's, modelos simples, exceções, tipos) não mostram o botão.', 
      'The methods checklist (button with a counter next to each file) is extracted automatically from the <code>function</code>/<code>procedure</code>/<code>construct'
    + 'or</code>/<code>destructor</code> declarations of each unit. This is a static-analysis heuristic, not a full Delphi parser — units without declared methods (DTO'
    + 's, simple models, exceptions, types) do not show the button.', 
      'La checklist des méthodes (bouton avec compteur à côté de chaque fichier) est extraite automatiquement des déclarations <code>function</code>/<code>procedure</c'
    + 'ode>/<code>constructor</code>/<code>destructor</code> de chaque unité. C''est une heuristique d''analyse statique, pas un analyseur Delphi complet — les unités sa'
    + 'ns méthodes déclarées (DTO, modèles simples, exceptions, types) n''affichent pas le bouton.', 
      'Die Methoden-Checkliste (Schaltfläche mit Zähler neben jeder Datei) wird automatisch aus den Deklarationen <code>function</code>/<code>procedure</code>/<code>co'
    + 'nstructor</code>/<code>destructor</code> jeder Unit extrahiert. Das ist eine Heuristik der statischen Analyse, kein vollständiger Delphi-Parser — Units ohne dek'
    + 'larierte Methoden (DTOs, einfache Modelle, Exceptions, Typen) zeigen die Schaltfläche nicht an.'),
  (
      'Para units com métodos, a caixa de conclusão do ficheiro deixa de ser manual: fica <strong style="color: var(--pending);">amarelo-escura</strong> enquanto houve'
    + 'r métodos por marcar e só passa a <strong style="color: var(--accent);">verde</strong> — unit totalmente implementada — quando todos os métodos estiverem marcad'
    + 'os.', 
      'For units with methods, the file''s completion box is no longer manual: it stays <strong style="color: var(--pending);">dark yellow</strong> while there are meth'
    + 'ods left to check and only turns <strong style="color: var(--accent);">green</strong> — unit fully implemented — when all methods are checked.', 
      'Pour les unités avec méthodes, la case de fin du fichier n''est plus manuelle : elle reste <strong style="color: var(--pending);">jaune foncé</strong> tant qu''il'
    + ' reste des méthodes à cocher et ne passe au <strong style="color: var(--accent);">vert</strong> — unité entièrement implémentée — que lorsque toutes les méthode'
    + 's sont cochées.', 
      'Bei Units mit Methoden ist das Erledigt-Feld der Datei nicht mehr manuell: Es bleibt <strong style="color: var(--pending);">dunkelgelb</strong>, solange Methode'
    + 'n noch nicht abgehakt sind, und wird erst <strong style="color: var(--accent);">grün</strong> — Unit vollständig umgesetzt — wenn alle Methoden abgehakt sind.'),
  ('return "Raiz";', 'return "Root";', 'return "Racine";', 'return "Stamm";'),
  ('<span>Métodos revistos</span>', '<span>Methods reviewed</span>', '<span>Méthodes revues</span>', '<span>Geprüfte Methoden</span>'),
  ('"Esta unit fica concluída automaticamente quando todos os métodos estiverem marcados."', '"This unit is completed automatically when all methods are checked."', '"Cette unité est terminée automatiquement lorsque toutes les méthodes sont cochées."', '"Diese Unit wird automatisch erledigt, sobald alle Methoden abgehakt sind."'),
  ('"última alteração: "', '"last change: "', '"dernière modification : "', '"letzte Änderung: "'),
  ('"Marcar prioridade"', '"Mark as priority"', '"Marquer comme prioritaire"', '"Als Priorität markieren"'),
  ('noteBtn.title = "Nota"', 'noteBtn.title = "Note"', 'noteBtn.title = "Note"', 'noteBtn.title = "Notiz"'),
  ('"Checklist de métodos desta unit"', '"Methods checklist of this unit"', '"Checklist des méthodes de cette unité"', '"Methoden-Checkliste dieser Unit"'),
  ('"Nota sobre este ficheiro…"', '"Note about this file…"', '"Note sur ce fichier…"', '"Notiz zu dieser Datei…"'),
  ('"Nenhum ficheiro corresponde aos filtros activos."', '"No file matches the active filters."', '"Aucun fichier ne correspond aux filtres actifs."', '"Keine Datei entspricht den aktiven Filtern."'),
  ('" / " + total + " ficheiros";', '" / " + total + " files";', '" / " + total + " fichiers";', '" / " + total + " Dateien";'),
  ('" de " + total + " ficheiros marcados"', '" of " + total + " files checked"', '" sur " + total + " fichiers cochés"', '" von " + total + " Dateien abgehakt"'),
  ('" / " + total + " ficheiros concluídos"', '" / " + total + " files done"', '" / " + total + " fichiers terminés"', '" / " + total + " Dateien erledigt"'),
  ('" métodos revistos"', '" methods reviewed"', '" méthodes revues"', '" Methoden geprüft"'),
  ('" &middot; impresso em "', '" &middot; printed on "', '" &middot; imprimé le "', '" &middot; gedruckt am "'),
  ('"Reiniciar o progresso, notas e prioridades de todos os "', '"Reset the progress, notes and priorities of all "', '"Réinitialiser la progression, les notes et les priorités de tous les "', '"Fortschritt, Notizen und Prioritäten aller "'),
  ('" ficheiros?"', '" files?"', '" fichiers ?"', '" Dateien zurücksetzen?"'),
  ('"Progresso reiniciado"', '"Progress reset"', '"Progression réinitialisée"', '"Fortschritt zurückgesetzt"'),
  ('"Progresso exportado"', '"Progress exported"', '"Progression exportée"', '"Fortschritt exportiert"'),
  ('"formato inválido"', '"invalid format"', '"format non valide"', '"ungültiges Format"'),
  ('"Progresso importado"', '"Progress imported"', '"Progression importée"', '"Fortschritt importiert"'),
  ('"Ficheiro inválido: "', '"Invalid file: "', '"Fichier non valide : "', '"Ungültige Datei: "'),
  ('" [Compila]"', '" [Builds]"', '" [Compile]"', '" [Kompiliert]"'),
  ('Checklist de Código-Fonte — __PROJECT_NAME_JS__', 'Source Code Checklist — __PROJECT_NAME_JS__', 'Checklist du code source — __PROJECT_NAME_JS__', 'Quellcode-Checkliste — __PROJECT_NAME_JS__'),
  ('"Markdown copiado"', '"Markdown copied"', '"Markdown copié"', '"Markdown kopiert"'),
  ('"Não foi possível copiar automaticamente."', '"Could not copy automatically."', '"Impossible de copier automatiquement."', '"Automatisches Kopieren nicht möglich."'),
  ('"Tema: "', '"Theme: "', '"Thème : "', '"Design: "'),
  ('" ficheiros · "', '" files · "', '" fichiers · "', '" Dateien · "'),
  ('" métodos em "', '" methods in "', '" méthodes dans "', '" Methoden in "'),
  ('"Linhas de código"', '"Lines of code"', '"Lignes de code"', '"Codezeilen"'),
  ('"Complexidade ciclomática"', '"Cyclomatic complexity"', '"Complexité cyclomatique"', '"Zyklomatische Komplexität"'),
  ('"Parâmetros"', '"Parameters"', '"Paramètres"', '"Parameter"'),
  ('"Aninhamento"', '"Nesting"', '"Imbrication"', '"Verschachtelung"'),
  ('"Complexidade cognitiva"', '"Cognitive complexity"', '"Complexité cognitive"', '"Kognitive Komplexität"')
  );

implementation

end.
